/* Datablock exports, typed linking, override inspection and live session state. */
const assetEdges=drawEdges,assetProblem=problem;
let selectedDataConnection=null;const assetFilters=new Map();
function liveSessions(n){return (state.live||[]).filter(s=>s.file&&normalize(s.file)===normalize(nodeFile(n)));}
problem=function(n){const live=liveSessions(n);return live.some(s=>s.dirty)?'Unsaved in Blender':live.length?'Open in Blender':assetProblem(n);};
function typeLabel(kind){return kind.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}
function localScenes(n){return (n.scan?.scenes||[]).filter(s=>!s.linked).map(s=>({value:s.name,label:s.name}));}
window.pipelineLinkDialog=function(source_id,target_id,collection){
  const source=state.project.nodes.find(n=>n.id===source_id),target=state.project.nodes.find(n=>n.id===target_id),detail=source.scan?.collection_details?.find(c=>c.name===collection);
  modal('Link '+collection,[{key:'mode',label:'Link mode',type:'select',options:[{value:'instance',label:'Collection instance · read-only asset'},{value:'collection',label:'Linked collection · objects / cameras'},{value:'override',label:'Editable library override hierarchy'}],help:'Local object changes and animation use overrides. A local material copy stops receiving source shader updates.'},{key:'scene',label:'Destination scene',type:'select',options:localScenes(target)},{key:'camera',label:'Set camera (optional)',type:'select',options:[{value:'',label:'Keep current camera'},...(detail?.cameras||[]).map(c=>({value:c,label:c}))]},closedField],v=>run('link',{source_id,target_id,collection,...v}));
  const mode=$('field-mode'),camera=$('field-camera');camera.disabled=true;mode.onchange=()=>{camera.disabled=mode.value==='instance';if(camera.disabled)camera.value='';};
};
function dataUsages(kind,tree){const uses=[{value:'keep',label:'Import reference only'}];if(kind==='materials')uses.push({value:'material',label:'Assign to first object material slot'});if(kind==='node_groups'&&tree==='GeometryNodeTree')uses.push({value:'modifier',label:'Add Geometry Nodes modifier'});if(kind==='node_groups'&&tree==='ShaderNodeTree')uses.push({value:'shader',label:'Create material using shader group'});if(kind==='worlds')uses.push({value:'world',label:'Use as scene world'});if(kind==='actions')uses.push({value:'animation',label:'Assign object animation'});if(kind==='objects')uses.push({value:'object',label:'Add object to scene'});return uses;}
function dataLinkDialog(source_id,target_id,preset){
  if(source_id===target_id)return error('Choose another destination file.');const source=state.project.nodes.find(n=>n.id===source_id),target=state.project.nodes.find(n=>n.id===target_id),data=source.scan?.datablocks||[];
  if(!data.length)return error('Refresh the source to read saved datablocks.');const kinds=[...new Set(data.map(d=>d.kind))].sort();
  modal('Link saved datablock',[{key:'kind',label:'Type',type:'select',options:kinds.map(k=>({value:k,label:typeLabel(k)}))},{key:'item',label:'Datablock',type:'select',options:[]},{key:'apply',label:'Use in destination',type:'select',options:[]},{key:'object_name',label:'Object for assignment',type:'select',options:[{value:'',label:'No object'},...(target.scan?.objects||[]).filter(o=>o.editable).map(o=>({value:o.name,label:o.name}))]},{key:'scene',label:'Destination scene',type:'select',options:localScenes(target)},{...closedField,help:'Import keeps a saved reference. Assignment is explicit. Embedded node trees must be exposed as reusable node groups before linking.'}],v=>run('link_data',{source_id,target_id,...v}));
  const kind=$('field-kind'),item=$('field-item'),use=$('field-apply'),object=$('field-object_name');kind.value=preset?.kind||kinds[0];
  function usageChanged(){object.disabled=!['material','modifier','shader','animation'].includes(use.value);if(object.disabled)object.value='';}
  function itemChanged(){const d=data.find(d=>d.kind===kind.value&&d.name===item.value);use.replaceChildren();for(const u of dataUsages(kind.value,d?.tree_type)){const o=el('option',u.label);o.value=u.value;use.append(o);}usageChanged();}
  function kindChanged(){item.replaceChildren();for(const d of data.filter(d=>d.kind===kind.value)){const o=el('option',d.name);o.value=d.name;item.append(o);}itemChanged();}
  kind.onchange=kindChanged;item.onchange=itemChanged;use.onchange=usageChanged;kindChanged();if(preset){item.value=preset.name;itemChanged();}
}
function chooseDataTarget(source,item){const targets=state.project.nodes.filter(n=>n.type==='blend'&&!n.external&&!n.hidden&&n.id!==source.id);if(!targets.length)return error('Create a destination Blend File first.');modal('Link '+item.name+' to a file',[{key:'target',label:'Destination',type:'select',options:targets.map(n=>({value:n.id,label:n.name}))}],v=>dataLinkDialog(source.id,v.target,item));}
PipelineUI.use('render','asset-ports',300,function(next){next();for(const n of visibleNodes().filter(n=>n.type==='blend')){const card=document.querySelector(`[data-id="${n.id}"]`);if(!card)continue;const row=el('div',undefined,'uxAssetRow');row.append(button('Materials / node groups / data',()=>{if(!inspectorOpen)inspectorToggle.click();inspectorTab='assets';pick(n.id);}));const port=el('span',undefined,'port assetOut');port.dataset.asset=n.id;port.title='Drag to a file to link a saved datablock';port.onpointerdown=e=>{e.stopPropagation();wire={asset:n.id};status('Drop on another Blend File');};row.append(port);card.querySelector('.renderOutput').before(row);}drawEdges();});
PipelineUI.use('pick','asset-selection',301,function(next, id,additive=false){selectedDataConnection=null;next(id,additive);});
PipelineUI.use('inspect','asset-details',302,function(next){
  if(selectedDataConnection){
    const c=selectedDataConnection,source=state.project.nodes.find(n=>n.id===c.source),target=state.project.nodes.find(n=>n.id===c.target);
    const unlink=button('Unlink reference',()=>modal('Unlink '+c.name,[{...closedField,help:'Remove assigned usages in Blender before unlinking.'}],v=>run('link_data',{source_id:c.source,target_id:c.target,kind:c.kind,item:c.name,closed:v.closed,unlink:true})));
    $('inspector').replaceChildren(section('Datablock connection',el('h3',c.name),muted(typeLabel(c.kind)+' · '+c.usage),muted(source.name+' → '+target.name),actions(button('Source',()=>pick(source.id)),button('Destination',()=>pick(target.id))),unlink));
    return;
  }
  const assetTab=inspectorTab==='assets';if(assetTab)inspectorTab='overview';next();if(assetTab)inspectorTab='assets';const n=state.project?.nodes.find(n=>n.id===selected);if(!n||n.type!=='blend')return;const pane=$('inspector'),tabs=pane.querySelector('.uxTabs');if(!tabs)return;
  const tab=button('Assets',()=>{inspectorTab='assets';inspect();});tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(assetTab));tab.classList.toggle('active',assetTab);tabs.append(tab);if(assetTab)for(const b of tabs.querySelectorAll('button:not(:last-child)')){b.classList.remove('active');b.setAttribute('aria-selected','false');}
  const content=pane.querySelector('.uxTabContent');
  if(assetTab){
    content.replaceChildren();const data=n.scan?.datablocks||[],filter=assetFilters.get(n.id)||{kind:'all',query:''},box=section('Saved datablocks',muted('Browse source exports and link them to another file. Assignment is optional.'));
    const kind=el('select');kind.setAttribute('aria-label','Asset type');for(const k of ['all',...[...new Set(data.map(d=>d.kind))].sort()]){const o=el('option',k==='all'?'All types':typeLabel(k));o.value=k;kind.append(o);}kind.value=filter.kind;const search=el('input');search.placeholder='Find datablock…';search.setAttribute('aria-label','Find datablock');search.value=filter.query;const list=el('div',undefined,'uxAssetList');box.append(kind,search,list);content.append(box);
    function paint(){filter.kind=kind.value;filter.query=search.value;assetFilters.set(n.id,filter);list.replaceChildren();const matches=data.filter(d=>(filter.kind==='all'||d.kind===filter.kind)&&d.name.toLowerCase().includes(filter.query.toLowerCase()));for(const d of matches.slice(0,150)){const row=el('div',undefined,'uxAssetItem');row.append(el('strong',d.name),muted(typeLabel(d.kind)+(d.tree_type?' · '+d.tree_type:'')),button('Link to file',()=>chooseDataTarget(n,d)));const socket=el('span',undefined,'port assetBrowserSocket');socket.title='Drag '+d.name+' to a file';socket.onpointerdown=e=>{e.stopPropagation();wire={asset:n.id,preset:d};status('Drop '+d.name+' onto a managed file');};row.append(socket);list.append(row);}if(!matches.length)list.append(muted('No matching saved datablocks.'));if(matches.length>150)list.append(muted('Filter to narrow '+matches.length+' results.'));}kind.onchange=paint;search.oninput=paint;paint();
    content.append(section('Reusable node setups',muted('A material’s embedded tree belongs to that material. Make reusable shader, Geometry Nodes or compositor setups into node groups first. Shader and geometry groups have explicit assignment options; other groups can be imported and placed in Blender.')));
  }
  if(inspectorTab==='overview'&&liveSessions(n).length)content.prepend(section('Live Blender',...liveSessions(n).map(s=>muted((s.dirty?'Unsaved edits':'Saved file')+' · Blender '+s.version+' · '+s.overrides+' overrides')),muted('Background edits are blocked while this file is open. Use the Pipeline sidebar for live linking.')));
  if(inspectorTab==='links'){
    const links=n.scan?.data_links||[];if(links.length)content.append(section('Linked datablocks',...links.map(d=>muted(typeLabel(d.kind)+' · '+d.name+' · '+d.usage))));const overrides=n.scan?.overrides||[];if(overrides.length){const box=section('Library overrides',muted(overrides.length+' overridden objects. Structural source changes still need review.'));for(const o of overrides){const detail=el('details');detail.append(el('summary',o.name+(o.system?' · system':' · editable')),muted('Source: '+o.reference+'\nAction: '+(o.action||'none')+'\nEdited properties: '+(o.properties.join(', ')||'none')));box.append(detail);}content.append(box);}
  }
});
drawEdges=function(){assetEdges();for(const target of state.project?.nodes.filter(n=>n.type==='blend'&&!n.hidden)||[])for(const data of target.scan?.data_links||[]){const source=state.project.nodes.find(n=>n.type==='blend'&&!n.hidden&&normalize(nodeFile(n))===normalize(data.source));if(!source)continue;const output=document.querySelector(`[data-asset="${source.id}"]`),input=document.querySelector(`[data-target="${target.id}"]`),a=output?point(output):nodeAnchor(source,'out'),b=input?point(input):nodeAnchor(target,'in');if(!a||!b)continue;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.style.stroke='#b59ac8';curve(path,a,b);const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=typeLabel(data.kind)+' · '+data.name+' → '+target.name;path.append(title);path.onclick=e=>{e.stopPropagation();selectedConnection=null;selectedDataConnection={...data,source:source.id,target:target.id};inspect();};$('edges').append(path);}};
const assetMove=$('workspace').onpointermove;$('workspace').onpointermove=e=>{if(wire?.asset){lastPoint=worldPoint(e.clientX,e.clientY);let preview=$('wirePreview');if(!preview){preview=document.createElementNS('http://www.w3.org/2000/svg','path');preview.id='wirePreview';preview.style.stroke='#b59ac8';preview.style.pointerEvents='none';$('edges').append(preview);}curve(preview,point(document.querySelector(`[data-asset="${wire.asset}"]`)),lastPoint);for(const card of document.querySelectorAll('.node.blend'))card.classList.toggle('uxDropTarget',card.dataset.id!==wire.asset);return;}assetMove(e);};
document.addEventListener('pointerup',e=>{if(!wire?.asset)return;e.stopImmediatePropagation();const source=wire.asset,preset=wire.preset,target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.node.blend')?.dataset.id;wire=null;$('wirePreview')?.remove();if(typeof clearLinkDrag==='function')clearLinkDrag();for(const card of document.querySelectorAll('.uxDropTarget'))card.classList.remove('uxDropTarget');if(target)dataLinkDialog(source,target,preset);else status('Link cancelled');},true);
if(state.project)render();

