/* Compact cards, searchable saved collection trees and external library actions. */
const compactEdges=drawEdges;
const collectionQueries=new Map(),collapsedCollections=new Map();
function affectedFiles(n){const files=state.project.nodes.filter(f=>f.type==='blend'),seen=new Set([n.id]),queue=[n],affected=[];while(queue.length){const source=queue.shift(),path=normalize(nodeFile(source));for(const target of files){if(seen.has(target.id)||!(target.scan?.refs||[]).some(r=>r.kind==='Library'&&normalize(r.path)===path))continue;seen.add(target.id);affected.push(target);queue.push(target);}}return affected;}
function highlightAffected(n){const files=affectedFiles(n);selection.clear();for(const f of [n,...files])selection.add(f.id);selected=n.id;render();controls.get('frameSelection').onclick();}
function collectionTree(details){const lookup=new Map(details.map(c=>[c.name,c])),seen=new Set(),ordered=[];function visit(c,ancestors=[]){if(seen.has(c.name))return;seen.add(c.name);ordered.push({...c,ancestors,browserDepth:ancestors.length});for(const child of c.children||[])if(lookup.has(child))visit(lookup.get(child),[...ancestors,c.name]);}for(const c of details)if(!(c.parents||[]).some(p=>lookup.has(p)))visit(c);for(const c of details)visit(c);return ordered;}
function browseCollections(n){if(!inspectorOpen)inspectorToggle.click();inspectorTab='collections';pick(n.id);}
function chooseCollectionTarget(n,c){const targets=state.project.nodes.filter(t=>t.type==='blend'&&!t.external&&!t.hidden&&t.id!==n.id);if(!targets.length)return error('Create a managed destination file first.');modal('Link '+c.name,[{key:'target_id',label:'Destination',type:'select',options:targets.map(t=>({value:t.id,label:t.name}))}],v=>window.pipelineLinkDialog(n.id,v.target_id,c.name));}
function collectLibrary(n){modal('Copy library into project',[{key:'title',label:'New folder name',value:'Imported Libraries',required:true},{...closedField,label:'All affected project files are saved and closed'}],v=>run('localize_external',{node_id:n.id,...v}));$('fields').append(muted('Copies this file and its external Blender library dependencies, then repairs registered project links. External originals stay unchanged. Pack textures and other non-library resources first. Recovery snapshots protect affected project files.'));}
addList.append(button('Register external library',()=>modal('Keep an external reference',[{key:'source',label:'External .blend path',required:true}],v=>run('external_register',v))));
PipelineUI.use('render','collection-summary',600,function(next){next();for(const n of visibleNodes().filter(n=>n.type==='blend')){const card=document.querySelector(`[data-id="${n.id}"]`);if(!card)continue;const caption=card.querySelector('.caption'),count=n.scan?.collection_details?.length||0;if(caption){caption.replaceChildren(button('Browse collections · '+count,()=>browseCollections(n)));caption.onclick=null;}
  if(n.external){card.classList.add('externalLibrary');card.querySelector('.rootWarning')?.remove();card.querySelector('.renderOutput')?.remove();card.querySelector('.nodeHistory')?.remove();const quick=card.querySelector('.uxNodeActions');if(quick)for(const b of quick.querySelectorAll('button'))if(b.title==='Snapshot saved file'||b.getAttribute('aria-label')==='Save snapshot')b.remove();card.querySelector('header').after(el('div','External library · referenced, not backed up','externalBadge'));}
}drawEdges();});
PipelineUI.use('inspect','collection-browser',601,function(next){const collectionTab=inspectorTab==='collections';if(collectionTab)inspectorTab='overview';next();if(collectionTab)inspectorTab='collections';const n=state.project?.nodes.find(n=>n.id===selected);if(!n||n.type!=='blend')return;const pane=$('inspector'),tabs=pane.querySelector('.uxTabs'),content=pane.querySelector('.uxTabContent');if(!tabs||!content)return;
const b=button('Collections',()=>browseCollections(n));b.setAttribute('role','tab');b.setAttribute('aria-selected',String(collectionTab));b.classList.toggle('active',collectionTab);tabs.append(b);if(collectionTab){for(const other of tabs.querySelectorAll('button:not(:last-child)')){other.classList.remove('active');other.setAttribute('aria-selected','false');}
content.replaceChildren();const details=collectionTree(n.scan?.collection_details||[]),search=el('input');search.placeholder='Find collection';search.setAttribute('aria-label','Find collection');search.value=collectionQueries.get(n.id)||'';const list=el('div',undefined,'collectionBrowser');content.append(section('Saved collections',muted(details.length+' collections · drag a socket to a file, or choose Link.'),search,list));const collapsed=collapsedCollections.get(n.id)||new Set();collapsedCollections.set(n.id,collapsed);
function paint(){collectionQueries.set(n.id,search.value);list.replaceChildren();const query=search.value.toLowerCase();const found=details.filter(c=>c.name.toLowerCase().includes(query)&& (query||!(c.ancestors||[]).some(p=>collapsed.has(p))));for(const c of found.slice(0,200)){const row=el('div',undefined,'collectionBrowserRow');row.style.paddingLeft=(query?0:Math.min(c.browserDepth||0,6)*10)+'px';if(c.children?.length)row.append(button(collapsed.has(c.name)?'▸':'▾',()=>{collapsed.has(c.name)?collapsed.delete(c.name):collapsed.add(c.name);paint();},collapsed.has(c.name)?'Expand children':'Collapse children'));const pin=button((n.pinned_collections||[]).includes(c.name)?'★':'☆',()=>{const pins=new Set(n.pinned_collections||[]);pins.has(c.name)?pins.delete(c.name):pins.add(c.name);editGraph(n,{pinned_collections:[...pins]});},(n.pinned_collections||[]).includes(c.name)?'Unpin collection from node':'Pin collection on node');row.append(pin,el('span',c.name),muted(c.objects+' objects'+(c.hidden?' · hidden':'')));const socket=el('span',undefined,'port collectionBrowserSocket');socket.title='Drag '+c.name+' to a destination';socket.classList.add('out');socket.dataset.source=n.id;socket.dataset.collection=c.name;socket.onpointerdown=e=>{e.stopPropagation();if(!c.objects)return error('Choose a non-empty collection.');wire={source:n.id,collection:c.name};status('Drop '+c.name+' on a managed file');};row.append(button('Link',()=>c.objects?chooseCollectionTarget(n,c):error('Choose a non-empty collection.')),socket);list.append(row);}if(!found.length)list.append(muted('No matching collections.'));if(found.length>200)list.append(muted('Search to narrow '+found.length+' results.'));}search.oninput=paint;paint();}
if(n.external){if(inspectorTab==='overview'||inspectorTab==='render'||inspectorTab==='history')content.replaceChildren(section('External library',el('p',nodeFile(n)||n.path,'uxPath'),muted('Referenced in place. Tool edits are disabled; project archives do not include this file.'),actions(button('Open Blender',()=>run('launch',{node_id:n.id})),button('Refresh',()=>run('refresh',{node_id:n.id}))),button('Map storage folder…',()=>modal('External library storage',[{key:'path',label:'Folder containing '+n.path,required:true}],v=>api('storage_map',{storage_id:n.storage_id,...v}).then(()=>run('refresh',{node_id:n.id})).catch(error))),button('Copy into project and repair links',()=>collectLibrary(n)),button('Browse collections',()=>browseCollections(n)),...(n.scan?.error?[el('p',n.scan.error,'warning')]:[])));
}else if(inspectorTab==='links'){const refs=(n.scan?.refs||[]).filter(r=>r.kind==='Library'&&!r.inside);if(refs.length)content.prepend(section('External libraries',...refs.map(r=>{const source=state.project.nodes.find(s=>normalize(nodeFile(s))===normalize(r.path));return section(r.name||r.raw,muted(r.exists?'Available outside project':'Missing library'),...(source?[button('Go to external node',()=>focusNode(source)),button('Copy into project',()=>collectLibrary(source))]:[]));})));}
if(inspectorTab==='overview'||inspectorTab==='links'){const used=affectedFiles(n);content.append(section('Affected files',muted(used.length?used.length+' files depend on this source, directly or through another library.':'No registered files depend on this source.'),...(used.length?[button('Highlight dependency impact',()=>highlightAffected(n)),...used.slice(0,12).map(f=>button(f.name,()=>focusNode(f)))]:[])));}
});
// Browser sockets initiate drags; persistent graph wires always anchor to graph cards.
function cardSocket(id,collection){return [...document.querySelectorAll('.node .out')].find(e=>e.dataset.source===id&&e.dataset.collection===collection);}
sourceSocket=function(id,collection){return cardSocket(id,collection)||[...document.querySelectorAll('.collectionBrowserSocket')].find(e=>e.dataset.source===id&&e.dataset.collection===collection);};
drawEdges=function(){const previewSocket=sourceSocket;sourceSocket=cardSocket;try{compactEdges();}finally{sourceSocket=previewSocket;}
for(const target of state.project?.nodes.filter(n=>n.type==='blend'&&!n.hidden)||[])for(const ref of target.scan?.refs||[]){if(ref.kind!=='Library'||ref.inside)continue;if([...(target.scan?.instances||[]),...(target.scan?.data_links||[])].some(i=>normalize(i.source)===normalize(ref.path)))continue;const source=state.project.nodes.find(n=>n.external&&!n.hidden&&normalize(nodeFile(n))===normalize(ref.path));if(!source)continue;const a=nodeAnchor(source,'out'),b=nodeAnchor(target,'in');if(!a||!b)continue;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.style.stroke='#b59ac8';path.style.strokeDasharray='6 4';curve(path,a,b);const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent='External library · '+source.name+' → '+target.name;path.append(title);path.onclick=()=>focusNode(source);$('edges').append(path);}
};
if(state.project)render();
