/* Node-to-node, multi-item linking. The graph is the place to start a link. */
const linkingMenu=nodeMenu;
const linkPreferences=new Map();
const primaryKinds=new Set(['collections','objects','materials','node_groups','worlds','actions']);
const assetKey=d=>JSON.stringify([d.kind,d.name]);
function savedAssets(n,advanced=false){
  const collections=(n.scan?.collection_details||[]).map(c=>({...c,kind:'collections'}));
  const order=['collections','objects','materials','node_groups','worlds','actions'];return [...collections,...(n.scan?.datablocks||[])].filter(d=>d.kind!=='collections'||collections.includes(d)).filter(d=>advanced||primaryKinds.has(d.kind)).sort((a,b)=>(order.indexOf(a.kind)<0?20:order.indexOf(a.kind))-(order.indexOf(b.kind)<0?20:order.indexOf(b.kind))||a.name.localeCompare(b.name,undefined,{numeric:true}));
}
function assetLabel(d){return d.kind==='objects'?(d.object_type==='MESH'?'Mesh object':d.object_type==='CAMERA'?'Camera':d.object_type==='LIGHT'?'Light':d.object_type==='ARMATURE'?'Rig':'Object'):d.kind==='node_groups'?'Node group':({meshes:'Mesh data',cameras:'Camera data',lights:'Light data',armatures:'Armature data',curves:'Curve data',grease_pencils:'Grease Pencil data',scenes:'Scene'})[d.kind]||typeLabel(d.kind).replace(/s$/,'');}
function assetIcon(d){return ({collections:'outliner_collection',materials:'material',node_groups:'nodetree',worlds:'world',actions:'time'})[d.kind]||'scene_data';}
function existingAssets(source,target){const path=normalize(nodeFile(source)),keys=new Set(),seen=new Set();function collection(name){if(seen.has(name))return;seen.add(name);keys.add(assetKey({kind:'collections',name}));const c=source.scan?.collection_details?.find(c=>c.name===name);for(const name of c?.members||[])keys.add(assetKey({kind:'objects',name}));for(const child of c?.children||[])collection(child);}for(const d of target.scan?.data_links||[])if(normalize(d.source)===path)keys.add(assetKey(d));for(const c of target.scan?.instances||[])if(normalize(c.source)===path)collection(c.collection);for(const o of target.scan?.overrides||[])if(normalize(o.source)===path)keys.add(assetKey({kind:'objects',name:o.reference}));for(const o of target.scan?.objects||[])if(o.source&&normalize(o.source)===path)keys.add(assetKey({kind:'objects',name:o.name}));return keys;}
function chooseBatchTarget(n,preset){const targets=state.project.nodes.filter(t=>t.type==='blend'&&!t.external&&!t.hidden&&t.id!==n.id);if(!targets.length)return error('Create a destination Blend File first.');modal('Link from '+n.name,[{key:'target_id',label:'Destination file',type:'select',options:targets.map(t=>({value:t.id,label:t.name+(reportedOpen(t)?' · open in Blender':'' )}))}],v=>batchLinkDialog(n.id,v.target_id,preset));}
function batchLinkDialog(source_id,target_id,preset){
  if(source_id===target_id)return status('Drop onto a different Blend File.');
  const source=state.project.nodes.find(n=>n.id===source_id),target=state.project.nodes.find(n=>n.id===target_id);
  if(!source||!target||target.external)return error('Choose a managed destination Blend File.');
  if(reportedOpen(target))return error('Close '+target.name+' in Blender first. Use the companion to link into an open file.');
  if(source.scan?.error||target.scan?.error)return error('Refresh these files and resolve their scan errors first.');
  const data=savedAssets(source,true),already=existingAssets(source,target),chosen=new Map(),preferences=linkPreferences.get(source_id+target_id)||{mode:'override'};
  if(preset){const d=data.find(d=>d.kind===preset.kind&&d.name===preset.name);if(d&&!already.has(assetKey(d)))chosen.set(assetKey(d),{...d,apply:d.kind==='objects'?'object':'keep',object_name:''});}
  modal('Link assets',[],()=>{});$('dialog').classList.add('linkDialog');$('submit').textContent='Link';
  const fields=$('fields'),route=el('div',undefined,'linkRoute');route.append(blenderIcon('file_blend'),el('strong',source.name),el('span','→'),blenderIcon('file_blend'),el('strong',target.name));fields.append(route);
  if(liveSessions(source).some(s=>s.dirty))fields.append(el('p','Source has unsaved edits. This links the last saved version. Save in Blender, then refresh the node to include new items.','warning'));
  const toolbar=el('div',undefined,'linkToolbar'),search=el('input'),filter=el('select'),advancedLabel=el('label',undefined,'linkCheck'),advanced=el('input');search.type='search';search.placeholder='Search saved assets…';search.setAttribute('aria-label','Search saved assets');filter.setAttribute('aria-label','Filter asset type');advanced.type='checkbox';advancedLabel.append(advanced,el('span','Raw data'));advancedLabel.title='Meshes, camera data and other low-level datablocks. Object linking already brings its data.';
  for(const [value,label] of [['all','All assets'],['collections','Collections'],['objects','Objects / cameras / lights'],['materials','Materials'],['node_groups','Node groups'],['worlds','Worlds'],['actions','Actions']]){const o=el('option',label);o.value=value;filter.append(o);}toolbar.append(search,filter,advancedLabel);fields.append(toolbar);
  const grid=el('div',undefined,'linkGrid'),browser=el('div',undefined,'linkBrowser'),selectionPane=el('div',undefined,'linkSelection'),list=el('div',undefined,'linkAssetList'),listActions=el('div',undefined,'linkListActions'),count=el('span'),all=button('Select visible',()=>{for(const d of visibleItems())if(!already.has(assetKey(d))&&!(d.kind==='collections'&&!d.objects))choose(d,true);paint();}),none=button('Clear',()=>{chosen.clear();paint();});listActions.append(count,all,none);browser.append(listActions,list);grid.append(browser,selectionPane);fields.append(grid);
  const settings=el('div',undefined,'linkSettings'),mode=el('select'),scene=el('select'),camera=el('select'),closed=el('input');
  for(const [value,label] of [['override','Library overrides'],['collection','Direct linked collections / objects'],['instance','Collection instances']]){const o=el('option',label);o.value=value;mode.append(o);}mode.value=preferences.mode;
  for(const s of localScenes(target)){const o=el('option',s.label);o.value=s.value;scene.append(o);}if(preferences.scene&&[...scene.options].some(o=>o.value===preferences.scene))scene.value=preferences.scene;
  function field(label,input){input.setAttribute('aria-label',label);const wrap=el('label',label);wrap.append(input);settings.append(wrap);return wrap;}field('Placement',mode);field('Destination scene',scene);field('Active camera',camera);fields.append(settings);
  const help=el('p',undefined,'linkHelp');fields.append(help);closed.type='checkbox';closed.id='batch-closed';const acknowledge=el('label',undefined,'linkCheck'),closedText=el('span','Destination is saved and closed in every Blender window');acknowledge.append(closed,closedText);let needsSourcePreparation=false;fields.append(acknowledge);
  const summary=el('div',undefined,'linkSummary'),overlapWarning=el('p',undefined,'warning');fields.append(overlapWarning,summary);
  function visibleItems(){const q=search.value.toLowerCase();return data.filter(d=>(advanced.checked||primaryKinds.has(d.kind))&&(filter.value==='all'||d.kind===filter.value)&&(d.name+' '+assetLabel(d)).toLowerCase().includes(q)).sort((a,b)=>{const order=['collections','objects','materials','node_groups','worlds','actions'];return (order.indexOf(a.kind)<0?20:order.indexOf(a.kind))-(order.indexOf(b.kind)<0?20:order.indexOf(b.kind))||a.name.localeCompare(b.name,undefined,{numeric:true});});}
  function choose(d,on){if(on){if(chosen.size>=200&&!chosen.has(assetKey(d)))return error('Select up to 200 items per operation.');chosen.set(assetKey(d),{...d,apply:d.kind==='objects'?'object':'keep',object_name:''});}else chosen.delete(assetKey(d));}
  function coverage(){const selected=[...chosen.values()].filter(d=>d.kind==='collections'),covered=new Set(),descendants=new Set();function visit(name){if(descendants.has(name))return;descendants.add(name);const c=data.find(d=>d.kind==='collections'&&d.name===name);for(const child of c?.children||[])visit(child);}for(const c of selected){for(const name of c.members||[])covered.add(name);for(const child of c.children||[])visit(child);}return {covered,descendants};}
  function paint(){
    const matches=visibleItems(),{covered,descendants}=coverage();count.textContent=matches.length+' assets';list.replaceChildren();
    for(const d of matches.slice(0,500)){const row=el('label',undefined,'linkAsset'),check=el('input'),text=el('span',undefined,'linkAssetText'),linked=already.has(assetKey(d)),empty=d.kind==='collections'&&!d.objects;check.type='checkbox';check.checked=chosen.has(assetKey(d));check.disabled=linked||empty;check.setAttribute('aria-label',d.name+' · '+assetLabel(d));check.onchange=()=>{choose(d,check.checked);paint();};row.classList.toggle('selected',check.checked);row.classList.toggle('unavailable',linked||empty);text.append(el('span',d.name),el('small',assetLabel(d)+(d.kind==='collections'?' · '+d.objects+' objects':d.kind==='objects'&&d.data_name?' · '+d.data_name:d.tree_type?' · '+d.tree_type.replace('NodeTree',''):'')));row.append(check,blenderIcon(assetIcon(d)),text);if(linked||empty||covered.has(d.name)&&d.kind==='objects'||descendants.has(d.name)&&d.kind==='collections')row.append(el('small',linked?'Linked':empty?'Empty':'Included','linkIncluded'));list.append(row);}
    if(!matches.length)list.append(muted('No matching saved assets. Save in Blender and refresh the source node.'));if(matches.length>500)list.append(muted('Search to narrow '+matches.length+' assets.'));
    selectionPane.replaceChildren(el('div',chosen.size+' selected','linkSelectionHeading'));
    for(const [key,d] of chosen){const row=el('div',undefined,'linkSelected'),label=el('div',undefined,'linkSelectedTitle');const remove=button('×',()=>{chosen.delete(key);paint();},'Deselect '+d.name);remove.setAttribute('aria-label','Deselect '+d.name);label.append(blenderIcon(assetIcon(d)),el('span',d.name),remove);row.append(label);
      const included=d.kind==='objects'&&covered.has(d.name)||d.kind==='collections'&&descendants.has(d.name);
      if(included)row.append(muted('Included by selected collection · added once'));
      else if(d.kind!=='collections'&&d.kind!=='objects'){
        const usage=el('select');usage.setAttribute('aria-label','Use '+d.name);for(const u of dataUsages(d.kind,d.tree_type)){const o=el('option',u.label);o.value=u.value;usage.append(o);}usage.value=d.apply;usage.onchange=()=>{d.apply=usage.value;paint();};row.append(usage);
        if(['material','modifier','shader','animation'].includes(d.apply)){const obj=el('select');obj.setAttribute('aria-label','Assign '+d.name+' to object');const empty=el('option','Choose destination object…');empty.value='';obj.append(empty);for(const o of (target.scan?.objects||[]).filter(o=>o.editable&&(!o.scenes||o.scenes.includes(scene.value)))){const option=el('option',o.name);option.value=o.name;obj.append(option);}obj.value=d.object_name;obj.onchange=()=>{d.object_name=obj.value;updateSummary();};row.append(obj);}
      }selectionPane.append(row);
    }if(!chosen.size)selectionPane.append(muted('Choose several collections, objects, materials or node groups. Object data comes with its object.'));
    paintSettings();updateSummary();
  }
  function paintSettings(){const names=new Set();for(const d of chosen.values()){if(d.kind==='objects')names.add(d.name);if(d.kind==='collections')for(const name of d.members||[])names.add(name);}const prepare=mode.value==='override'&&data.some(d=>d.kind==='objects'&&d.object_type==='MESH'&&names.has(d.name)&&(d.material_slot_count||0)===0);if(prepare!==needsSourcePreparation)closed.checked=false;needsSourcePreparation=prepare;closedText.textContent=prepare?'Source and destination are saved and closed in every Blender window':'Destination is saved and closed in every Blender window';const before=camera.value,cameras=new Set();for(const d of chosen.values()){if(d.kind==='collections'&&mode.value!=='instance')for(const c of d.cameras||[])cameras.add(c);if(d.kind==='objects'&&d.object_type==='CAMERA'&&!(mode.value==='instance'&&coverage().covered.has(d.name)))cameras.add(d.name);}camera.replaceChildren();for(const name of ['',...cameras]){const o=el('option',name||'Keep current camera');o.value=name;camera.append(o);}if(cameras.has(before))camera.value=before;
    help.textContent=mode.value==='override'?'Collections and objects become editable override hierarchies. Materials and node groups stay linked. Object material slots preserve local assignments.'+(needsSourcePreparation?' Empty source slots will be prepared with a recovery snapshot; close the source first.':''):mode.value==='instance'?'Collections are placed as instances. Standalone objects are added directly. Materials and node groups remain linked references.':'Collections and objects are added directly and keep their source links. Materials and node groups are kept as references unless assigned above.';
  }
  function updateSummary(){const {covered,descendants}=coverage(),effective=[...chosen.values()].filter(d=>!(d.kind==='objects'&&covered.has(d.name)||d.kind==='collections'&&descendants.has(d.name)));summary.textContent=chosen.size+' selected · '+effective.length+' additions · one recovery snapshot';$('submit').textContent='Link '+effective.length+' item'+(effective.length===1?'':'s');const roots=effective.filter(d=>d.kind==='collections'),seen=new Set();let overlap=false;for(const c of roots){for(const member of c.members||[]){if(seen.has(member))overlap=true;seen.add(member);}}const overridden=new Set((target.scan?.overrides||[]).filter(o=>normalize(o.source)===normalize(nodeFile(source))).map(o=>o.reference)),existingOverlap=mode.value!=='instance'&&roots.some(c=>(c.members||[]).some(name=>overridden.has(name))),blocked=mode.value==='override'&&overlap||existingOverlap;overlapWarning.textContent=existingOverlap?'A selected collection shares objects with an existing override hierarchy. Extend that hierarchy in Blender to avoid duplicates.':blocked?'These collections share objects. Select their common parent for one override hierarchy, or choose direct linking to avoid duplicates.':'';overlapWarning.hidden=!blocked;$('submit').disabled=!effective.length||blocked;}
  search.oninput=paint;filter.onchange=paint;advanced.onchange=()=>{const previous=filter.value;for(const o of [...filter.options])if(o.dataset.raw)o.remove();if(advanced.checked)for(const kind of [...new Set(data.map(d=>d.kind))].filter(k=>!primaryKinds.has(k)).sort()){const o=el('option',assetLabel({kind}));o.value=kind;o.dataset.raw='true';filter.append(o);}filter.value=[...filter.options].some(o=>o.value===previous)?previous:'all';paint();};mode.onchange=()=>{paintSettings();updateSummary();};scene.onchange=paint;closed.onchange=()=>closed.setCustomValidity('');
  $('form').onsubmit=e=>{e.preventDefault();if(!chosen.size||$('submit').disabled)return;if(!closed.checked){closed.setCustomValidity('Confirm the destination is saved and closed.');return closed.reportValidity();}const items=[...chosen.values()].map(d=>({kind:d.kind,name:d.name,apply:d.apply,object_name:d.object_name}));if(items.some(d=>['material','modifier','shader','animation'].includes(d.apply)&&!d.object_name))return error('Choose a destination object for each assignment.');linkPreferences.set(source_id+target_id,{mode:mode.value,scene:scene.value});$('dialog').close();run('link_batch',{source_id,target_id,items,mode:mode.value,scene:scene.value,camera:camera.value,closed:true,prepare_source:needsSourcePreparation});};
  paint();search.focus();
}
$('dialog').addEventListener('close',()=>{if($('dialog').open)return; $('dialog').classList.remove('linkDialog');$('submit').textContent='Confirm';$('submit').disabled=false;});
dataLinkDialog=batchLinkDialog;
window.pipelineLinkDialog=(source,target,collection)=>batchLinkDialog(source,target,{kind:'collections',name:collection});
PipelineUI.use('render','link-sockets',1200,function(next){next();for(const n of visibleNodes().filter(n=>n.type==='blend')){const card=document.querySelector(`[data-id="${n.id}"]`);if(!card)continue;const row=card.querySelector('.uxAssetRow');if(row){const port=row.querySelector('.assetOut');row.replaceChildren(button('Link assets…',()=>chooseBatchTarget(n),'Choose assets to link to another file'),port);port.title='Drag onto another Blend File, then choose several assets';port.setAttribute('role','button');port.setAttribute('tabindex','0');port.setAttribute('aria-label','Link assets from '+n.name);port.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseBatchTarget(n);}};port.onpointerdown=e=>{if(e.button!==0||busy)return;e.preventDefault();e.stopPropagation();wire={asset:n.id};document.body.classList.add('linkDragging');status('Drop on a destination file · select assets together');};}
  const input=card.querySelector('.uxInputRow');if(input){input.childNodes[0].textContent='Linked assets';input.title='Drop assets from another file anywhere on this node';}
  const caption=card.querySelector('.caption');if(caption){caption.replaceChildren(button('Contents · '+savedAssets(n).length,()=>{if(!inspectorOpen)inspectorToggle.click();inspectorTab='contents';pick(n.id);}));}
  for(const socket of card.querySelectorAll('.collection .out'))socket.title='Drag '+socket.dataset.collection+' to a file · preselected in multi-link picker';
}drawEdges();});
PipelineUI.use('inspect','link-contents',1201,function(next){const contents=['assets','collections','contents'].includes(inspectorTab);if(contents)inspectorTab='overview';next();if(contents)inspectorTab='contents';const n=state.project?.nodes.find(n=>n.id===selected);if(!n||n.type!=='blend'||selectedConnection||selectedDataConnection)return;const tabs=$('inspector').querySelector('.uxTabs'),content=$('inspector').querySelector('.uxTabContent');if(!tabs||!content)return;for(const b of [...tabs.children])if(['Assets','Collections'].includes(b.textContent.trim()))b.remove();const tab=button('Contents',()=>{inspectorTab='contents';inspect();});tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(contents));tab.classList.toggle('active',contents);tabs.append(tab);if(contents){for(const b of tabs.children)if(b!==tab){b.classList.remove('active');b.setAttribute('aria-selected','false');}content.replaceChildren();const box=section('Saved contents',muted('Objects include their mesh or camera data. Start a link from the node’s purple socket.')),search=el('input'),list=el('div');search.type='search';search.placeholder='Find saved content…';search.setAttribute('aria-label','Find saved content');box.append(search,list);content.append(box);function paint(){list.replaceChildren();const matches=savedAssets(n).filter(d=>d.name.toLowerCase().includes(search.value.toLowerCase()));for(const d of matches.slice(0,100)){const row=el('div',undefined,'contentsItem');row.append(blenderIcon(assetIcon(d)),el('span',d.name),el('small',assetLabel(d)));list.append(row);}if(matches.length>100)list.append(muted('Search to narrow '+matches.length+' items.'));if(!matches.length)list.append(muted('No matching saved contents.'));}search.oninput=paint;paint();}});
nodeMenu=function(n,anchor){linkingMenu(n,anchor);if(n.type==='blend')$('contextMenu').prepend(button('Link assets to file…',()=>chooseBatchTarget(n)));};
const linkingMove=$('workspace').onpointermove;$('workspace').onpointermove=e=>{linkingMove(e);if(wire?.asset||wire?.source){const under=document.elementFromPoint(e.clientX,e.clientY)?.closest('.node.blend');for(const card of document.querySelectorAll('.node.blend')){const n=state.project.nodes.find(n=>n.id===card.dataset.id),valid=n.id!==(wire.asset||wire.source)&&!n.external&&!reportedOpen(n);card.classList.toggle('uxDropTarget',valid);card.classList.toggle('linkDropHover',valid&&card===under);}document.body.classList.add('linkDragging');}};
function clearLinkDrag(){document.body.classList.remove('linkDragging');for(const card of document.querySelectorAll('.uxDropTarget,.linkDropHover'))card.classList.remove('uxDropTarget','linkDropHover');}
document.addEventListener('pointerup',clearLinkDrag,true);
document.addEventListener('pointercancel',()=>{if(wire?.asset||wire?.source){wire=null;$('wirePreview')?.remove();clearLinkDrag();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){wire=null;$('wirePreview')?.remove();clearLinkDrag();}});
if(state.project)render();


/* One cable per file pair; inspect or extend the entire connection in context. */
const linkingEdges=drawEdges;
function connectionItems(source,target){const path=normalize(nodeFile(source));return [...(target.scan?.instances||[]).filter(d=>normalize(d.source)===path).map(d=>({...d,kind:'collections',name:d.collection})),...(target.scan?.data_links||[]).filter(d=>normalize(d.source)===path)];}
function connectionDialog(source,target){const items=connectionItems(source,target);modal('Linked assets',[],()=>{});$('submit').hidden=true;const route=el('div',source.name+' → '+target.name,'linkRoute');$('fields').append(route,button('Add more assets…',()=>{$('dialog').close();batchLinkDialog(source.id,target.id);}));for(const d of items){const row=el('div',undefined,'connectionItem');row.append(blenderIcon(assetIcon(d)),el('span',d.name),muted(assetLabel(d)+(d.mode?' · '+d.mode:d.usage?' · '+d.usage:'')));if(d.kind==='collections'&&!d.direct)row.append(button('Unlink',()=>modal('Unlink '+d.name,[closedField],v=>run('link',{source_id:source.id,target_id:target.id,collection:d.name,closed:v.closed,unlink:true}))));else if(d.kind!=='collections'&&!(d.kind==='objects'&&(target.scan?.overrides||[]).some(o=>o.reference===d.name&&normalize(o.source)===normalize(nodeFile(source)))))row.append(button('Unlink',()=>modal('Unlink '+d.name,[{...closedField,help:'Assigned data and overridden objects must be removed in Blender first.'}],v=>run('link_data',{source_id:source.id,target_id:target.id,kind:d.kind,item:d.name,closed:v.closed,unlink:true}))));else row.append(el('small','Edit hierarchy in Blender'));$('fields').append(row);}}
const linkingModal=modal;modal=function(...args){$('submit').hidden=false;linkingModal(...args);};
drawEdges=function(){linkingEdges();for(const path of [...$('edges').querySelectorAll('path')])if(path.id!=='wirePreview'&&!path.querySelector('title')?.textContent.includes(' renders → '))path.remove();const nodes=visibleNodes().filter(n=>n.type==='blend');for(const target of nodes)for(const source of nodes){if(source===target)continue;const items=connectionItems(source,target),ref=(target.scan?.refs||[]).some(r=>r.kind==='Library'&&normalize(r.path)===normalize(nodeFile(source)));if(!items.length&&!ref)continue;const port=document.querySelector(`[data-asset="${source.id}"]`),input=document.querySelector(`[data-target="${target.id}"]`),a=port?point(port):nodeAnchor(source,'out'),b=input?point(input):nodeAnchor(target,'in');if(!a||!b)continue;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.style.stroke='#b49bc9';if(source.external)path.style.strokeDasharray='6 4';curve(path,a,b);const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=source.name+' → '+target.name+' · '+items.length+' assets · click to inspect or add';path.append(title);path.onclick=e=>{e.stopPropagation();connectionDialog(source,target);};$('edges').append(path);}};
if(state.project)render();

// Keep details focused on this file; project tools stay in the project view.

PipelineUI.use('inspect','link-details',1202,function(next){next();const n=state.project?.nodes.find(n=>n.id===selected);if(!n||n.type!=='blend')return;for(const box of $('inspector').querySelectorAll('.uxSection'))if(['Render queue','Blender companion'].includes(box.querySelector('h4')?.textContent.trim()))box.remove();const tabs=$('inspector').querySelector('.uxTabs');if(tabs){for(const tab of tabs.children){tab.tabIndex=tab.getAttribute('aria-selected')==='true'?0:-1;tab.onkeydown=e=>{const keys=['ArrowLeft','ArrowRight','Home','End'];if(!keys.includes(e.key))return;e.preventDefault();const buttons=[...tabs.children],index=buttons.indexOf(tab),next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;const label=buttons[next].textContent.trim();buttons[next].click();[...$('inspector').querySelectorAll('.uxTabs button')].find(b=>b.textContent.trim()===label)?.focus();};}}
  if(inspectorTab==='contents'){for(const row of $('inspector').querySelectorAll('.contentsItem')){const name=row.querySelector('span:not(.blIcon)')?.textContent;if(!n.scan?.collection_details?.some(c=>c.name===name))continue;const pins=n.pinned_collections||[],pinned=pins.includes(name),pin=button(pinned?'★':'☆',()=>editGraph(n,{pinned_collections:pinned?pins.filter(c=>c!==name):[...pins,name]}),pinned?'Unpin collection on node':'Pin collection on node');pin.setAttribute('aria-label',(pinned?'Unpin ':'Pin ')+name);row.append(pin);}}
});

PipelineUI.use('render','linked-summary',1203,function(next){next();for(const n of visibleNodes().filter(n=>n.type==='blend')){const card=document.querySelector(`[data-id="${n.id}"]`);if(!card)continue;card.querySelector('.body>.empty')?.remove();card.querySelector('.rootWarning')?.remove();const input=card.querySelector('[data-target]');if(input)input.title='Drop assets from another Blend File here';const links=n.scan?.data_links||[];if(links.length){const summary=el('div',links.length+' linked datablock'+(links.length===1?'':'s'),'uxIncoming');card.querySelector('.uxInputRow')?.after(summary);}for(const port of card.querySelectorAll('.collection .out')){const previous=port.onpointerdown;port.onpointerdown=e=>{e.preventDefault();previous(e);if(wire?.source)document.body.classList.add('linkDragging');};}}drawEdges();});
if(state.project)render();


function prepareNodeMaterials(n){modal('Persistent material assignments',[{...closedField,label:'This file and its object source files are saved and closed',help:'Creates missing source material slots and switches override assignments to Object. Every affected file gets a recovery snapshot. Reassign any material already lost during reopening.'}],v=>run('prepare_materials',{node_id:n.id,closed:v.closed}));}
const materialNodeMenu=nodeMenu;nodeMenu=function(n,anchor){materialNodeMenu(n,anchor);if(n.type==='blend'&&!n.external){const b=button('Prepare material assignments',()=>prepareNodeMaterials(n));b.disabled=reportedOpen(n);$('contextMenu').append(b);}};
PipelineUI.use('inspect','material-assignment-safety',1204,function(next){next();const n=state.project?.nodes.find(n=>n.id===selected);if(!n||n.type!=='blend'||n.external||inspectorTab!=='links')return;const objects=(n.scan?.objects||[]).filter(o=>o.reference),unsafe=objects.filter(o=>o.reference_slots===0||o.material_slots?.some(s=>s.link==='DATA'));if(unsafe.length)$('inspector').querySelector('.uxTabContent')?.prepend(section('Material assignments',muted(unsafe.length+' overridden objects need Object slots or source slot preparation.'),button('Prepare material assignments',()=>prepareNodeMaterials(n))));});
