/* Render targets are explicit blue output connections, never folder membership. */
const renderSettings=[['width','Width','number'],['height','Height','number'],['percentage','Scale %','number'],['samples','Samples','number'],['start','First frame','number'],['end','Last frame','number'],['step','Frame step','number'],['engine','Engine',[['CYCLES','Cycles'],['BLENDER_EEVEE','EEVEE']]],['format','Format',[['PNG','PNG'],['OPEN_EXR','OpenEXR'],['OPEN_EXR_MULTILAYER','Multilayer EXR'],['JPEG','JPEG'],['FFMPEG','Video (saved encoding)']]],['denoise','Cycles denoising',[[true,'On'],[false,'Off']]]];
function outputTargets(folderId=null){const all=state.project?.nodes||[],root=all.find(n=>n.id===folderId),allowed=new Set(all.filter(n=>n.type==='folder'&&(!root||n.id===root.id||inFrame(n,root.id)||n.path.startsWith(root.path+'/'))).map(n=>n.id));return all.filter(n=>n.type==='blend'&&!n.external&&allowed.has(n.render_config?.folder_id));}
folderRuns=function(n){return [...(state.project?.renders||[])].reverse().filter(r=>r.status!=='Deleted'&&(r.output===n.path||r.output.startsWith(n.path+'/')));};
function folderHasRendering(n){return outputTargets(n.id).length>0||folderRuns(n).length>0;}
function savedSetupSettings(scene,viewLayer=''){
  if(scene.engine!=='CYCLES'||!scene.view_layers?.length)return scene;
  const layers=scene.view_layers.filter(l=>viewLayer?l.name===viewLayer:l.enabled),samples=[...new Set(layers.map(l=>scene.layer_samples==='IGNORE'?scene.samples:scene.layer_samples==='BOUNDED'?Math.min(l.samples||scene.samples,scene.samples):l.samples||scene.samples))];
  return samples.length?{...scene,samples:samples.length===1?samples[0]:null,per_layer_samples:samples.length>1}:scene;
}
function savedRender(n){const scene=(n.render_config?.scene?n.scan?.scenes?.find(s=>s.name===n.render_config.scene&&!s.linked):n.scan?.scenes?.find(s=>!s.linked))||{};return savedSetupSettings(scene,n.render_config?.view_layer);}
function renderTargetReady(n,overrides={}){const scene=savedRender(n);return !!scene.name&&(scene.cameras||[]).includes(n.render_config?.camera||scene.camera)&&(!n.render_config?.view_layer||(scene.view_layers||[]).some(l=>l.name===n.render_config.view_layer))&&!(window.pipelineRenderIssues?.(n,overrides)||[]).length;}
function effectiveSettings(n,overrides={}){const saved=savedRender(n),config=n.render_config||{},values={...saved};for(const [k,v] of Object.entries(config))if(v!==null&&v!==undefined)values[k]=v;return {...values,...overrides};}
function renderSettingOrigin(n,key,overrides={}){if(key in overrides)return 'Batch override';const operation=state.project.nodes.find(o=>o.id===n.operation_id),target=operation?.render_plan.targets.find(t=>t.id===n.target_id);if(operation?.render_plan.overrides[key]!=null)return 'Render override';if(target?.overrides[key]!=null||!operation&&n.render_config?.[key]!=null)return 'Setup override';return 'Saved in Blender';}
function sizeLabel(bytes){return bytes>=1073741824?(bytes/1073741824).toFixed(1)+' GB':bytes>=1048576?(bytes/1048576).toFixed(1)+' MB':Math.ceil((bytes||0)/1024)+' KB';}
function settingEditor(parent,initial={},saved={},onchange=()=>{},key='common'){
  const grid=el('div',undefined,'rmSettingsWrap'),controls=new Map();parent.append(grid);
  const groups=[['Resolution',['width','height','percentage']],['Sampling',['samples','denoise']],['Frames',['start','end','step']],['Engine / format',['engine','format']]];
  for(const [name,keys] of groups){
    const group=renderPanel(name,key+':'+name,false),rows=el('div',undefined,'rmSettings');group.classList.add('rmSettingGroup');group.append(rows);grid.append(group);
    for(const [prop,label,type] of renderSettings.filter(s=>keys.includes(s[0]))){
      const row=el('div',undefined,'rmSetting'),check=el('input');check.type='checkbox';check.checked=initial[prop]!=null;check.setAttribute('aria-label','Override '+label);const title=el('label',label);title.prepend(check);const input=el(Array.isArray(type)?'select':'input');input.setAttribute('aria-label',label);
      if(Array.isArray(type)){for(const [value,text] of type){const o=el('option',text);o.value=String(value);input.append(o);}}else{input.type=type;input.step='1';if(!['start','end'].includes(prop))input.min='1';}
      const fallback=prop==='samples'?64:prop==='percentage'?100:prop==='engine'?'CYCLES':prop==='format'?'PNG':prop==='denoise'?true:prop==='width'?1920:prop==='height'?1080:prop==='start'||prop==='step'?1:250;
      input.value=String(initial[prop]??saved[prop]??(check.checked?fallback:''));input.placeholder=prop==='samples'&&saved.per_layer_samples?'Per layer':'Per setup';input.disabled=!check.checked;
      const hint=el('small',check.checked?'Override':'Saved','rmOrigin');row.append(title,input,hint);row.title='Enable to override '+label+'. Unchecked values use this setup’s saved Blender setting.';rows.append(row);controls.set(prop,{check,input});
      function count(){group.querySelector('summary').dataset.count=keys.filter(k=>controls.get(k)?.check.checked).length||'';}
      check.onchange=()=>{input.disabled=!check.checked;if(check.checked&&!input.value)input.value=String(fallback);hint.textContent=check.checked?'Override':'Saved';row.classList.toggle('enabled',check.checked);count();onchange(read());};input.oninput=()=>onchange(read());row.classList.toggle('enabled',check.checked);count();
    }
  }
  function read(){const values={};for(const [prop,{check,input}] of controls)if(check.checked)values[prop]=prop==='denoise'?input.value==='true':['engine','format'].includes(prop)?input.value:Number(input.value);return values;}
  return {read,reset(){for(const {check,input} of controls.values()){check.checked=false;input.disabled=true;check.onchange();}},grid};
}
const renderCatalogCache=new Map();async function loadRenderSettings(n){const key=[state.project.id,n.id,n.scan?.hash,n.scan?.scanned_at].join(':');if(renderCatalogCache.has(key))return renderCatalogCache.get(key);if(renderCatalogCache.size>=30)renderCatalogCache.clear();const request=api('read_render_settings',{node_id:n.id}).then(result=>result.scenes).catch(error=>{renderCatalogCache.delete(key);throw error;});renderCatalogCache.set(key,request);return request;}
configureRender=async function(n,folderId){
  let catalogue;try{catalogue=await loadRenderSettings(n);}catch(e){return error(e);}const scenes=(n.scan?.scenes||[]).filter(s=>!s.linked).map(s=>({...s,advanced_settings:catalogue[s.name]||[]})),config=n.render_config||{},scene=scenes.find(s=>s.name===config.scene)||scenes.find(s=>s.camera)||scenes[0];if(!scene)return error('Refresh this file to read its saved scenes.');const options=folders().filter(f=>f.value);if(!options.length)return error('Drag the blue output socket onto empty canvas to create an output folder.');
  let editor,advancedEditor;
  modal('Render settings · '+n.name,[{key:'folder_id',label:'Output folder',type:'select',options,value:folderId||config.folder_id||options[0].value},{key:'scene',label:'Scene',type:'select',options:scenes.map(s=>({label:s.name,value:s.name})),value:scene.name},{key:'camera',label:'Camera',type:'select',options:[{label:'Saved active camera',value:''},...scene.cameras.map(c=>({label:c,value:c}))],value:config.camera||''},{key:'auto_prefix',label:'Automatic date + scene filename',type:'checkbox',value:config.auto_prefix??true},{key:'prefix',label:'Filename prefix',value:config.prefix||renderPrefix(scene.name)}],v=>{
    delete v[''];const values=Object.fromEntries(renderSettings.map(([key])=>[key,null]));Object.assign(values,editor.read());run('render_config',{node_id:n.id,...v,...values,advanced:advancedEditor.read()});
  });
  $('fields').append(muted('Unchecked settings inherit the saved Blender scene. Render jobs change frozen copies; your working file keeps its settings and passes.'));
  editor=settingEditor($('fields'),config,scene);$('submit').textContent='Save settings';
  advancedEditor=advancedSettingsEditor($('fields'),scene,config.advanced||{});
  const prefix=()=>{$('field-prefix').readOnly=$('field-auto_prefix').checked;if($('field-auto_prefix').checked)$('field-prefix').value=renderPrefix($('field-scene').value);};$('field-auto_prefix').onchange=prefix;prefix();
  $('field-scene').onchange=()=>{const s=scenes.find(s=>s.name===$('field-scene').value);$('field-camera').replaceChildren();for(const c of ['',...s.cameras]){const o=el('option',c||'Saved active camera');o.value=c;$('field-camera').append(o);}editor.grid.remove();editor=settingEditor($('fields'),{},s);advancedEditor.root.remove();advancedEditor=advancedSettingsEditor($('fields'),s,{});prefix();};
};
window.pipelineCreateRenderFolder=function(n,p){const scene=savedRender(n),existing=new Set(state.project.nodes.filter(f=>f.type==='folder').map(f=>f.path));let title='Out_'+(scene.name||n.name),count=2;while(existing.has(title))title='Out_'+(scene.name||n.name)+'_'+count++;
  modal('Create an output folder here?',[{key:'title',label:'Folder name',value:title,required:true}],async v=>{const before=new Set(state.project.nodes.map(n=>n.id)),next=await run('folder',{title:v.title,...p,width:350,height:240});if(!next)return;const folder=next.project.nodes.find(f=>!before.has(f.id));if(!folder)return;const s=savedRender(n);if(!s.camera)return configureRender(n,folder.id);const config=n.render_config||{scene:s.name,camera:'',start:null,end:null,percentage:null,auto_prefix:true};const result=await run('render_config',{node_id:n.id,...config,folder_id:folder.id});if(result)status('Output connected · click Render on the file, or Rendering on its folder.');});$('fields').append(muted('Creates a regular folder with an explicit output connection. Each render gets a separate numbered version.'));$('submit').textContent='Create + connect';
};

const renderManager=el('dialog');renderManager.id='renderManager';document.body.append(renderManager);let rm=null;
function syncRenderingToggle(){const open=renderManager.open;activity.classList.toggle('active',open);activity.setAttribute('aria-pressed',String(open));activity.title=open?'Return to graph':'Render targets, batch overrides, queue and versions';document.body.classList.toggle('renderWorkspace',open);}
function closeRenderManager(){renderManager.close();syncRenderingToggle();}
renderManager.setAttribute('aria-label','Rendering workspace');activity.setAttribute('aria-controls','renderManager');syncRenderingToggle();renderManager.addEventListener('close',()=>{if(renderManager.open)return;rm=null;syncRenderingToggle();activity.focus();});
function openRenderManager(scope=null,nodeIds=null){if(!state.project)return;if(PipelineUI.outputs?.isOpen())PipelineUI.outputs.close();const target=state.project.nodes.find(n=>n.id===scope),initial=scope?(target?.render_overrides||{}):(state.project.render_overrides||{});rm={project:state.project.id,scope,nodeIds,tab:'targets',checked:new Set((nodeIds?outputTargets(scope).filter(n=>nodeIds.includes(n.id)):outputTargets(scope)).map(n=>n.id)),draft:{...initial},label:'',notice:'',settingsOpen:false,versionLimit:20,versionSearch:'',versionSort:'newest',signature:''};document.body.classList.add('renderWorkspace');paintRenderManager();if(!renderManager.open)renderManager.show();syncRenderingToggle();}
const renderFocusNode=focusNode;focusNode=function(n){if(renderManager.open)closeRenderManager();if(PipelineUI.outputs?.isOpen())PipelineUI.outputs.close();renderFocusNode(n);};
const renderPlaceFile=startPlacement;startPlacement=function(...args){if(renderManager.open)closeRenderManager();if(PipelineUI.outputs?.isOpen())PipelineUI.outputs.close();return renderPlaceFile(...args);};
const renderCreateFolder=createFolderHere;createFolderHere=function(...args){if(renderManager.open)closeRenderManager();if(PipelineUI.outputs?.isOpen())PipelineUI.outputs.close();return renderCreateFolder(...args);};
function managerTargets(){return outputTargets(rm.scope).filter(n=>!rm.nodeIds||rm.nodeIds.includes(n.id));}
function queueInFolder(job,root){const folder=state.project.nodes.find(n=>n.id===(job.effective_settings||job.settings||job.config)?.folder_id);return !!folder&&(folder.id===root.id||inFrame(folder,root.id)||folder.path.startsWith(root.path+'/'));}
function queueInScope(job,targets){
  if(!rm.scope&&!rm.nodeIds)return true;
  if(state.project.nodes.some(n=>n.id===rm.scope&&n.type==='render'))return job.operation_id===rm.scope;
  if(targets.some(n=>n.id===(job.target_key||job.node_id)))return true;
  const root=state.project.nodes.find(n=>n.id===rm.scope&&n.type==='folder'),folder=state.project.nodes.find(n=>n.id===(job.effective_settings||job.settings)?.folder_id);
  return !!root&&!!folder&&(folder.id===root.id||inFrame(folder,root.id)||folder.path.startsWith(root.path+'/'));
}
function scopeRuns(){const scope=state.project.nodes.find(n=>n.id===rm.scope);if(scope?.type==='render')return [...(state.project.renders||[])].reverse().filter(r=>r.status!=='Deleted'&&r.operation_id===scope.id);const ids=new Set(managerTargets().map(n=>n.id)),folders=state.project.nodes.filter(n=>n.type==='folder'&&(!scope||n.id===scope.id||inFrame(n,scope.id)||n.path.startsWith(scope.path+'/')));return [...(state.project.renders||[])].reverse().filter(r=>r.status!=='Deleted'&&(!rm.scope&&!rm.nodeIds||rm.nodeIds&&ids.has(r.operation_id?r.operation_id+':'+r.target_id:r.node_id)||rm.scope&&folders.some(f=>r.output.startsWith(f.path+'/'))));}
function paintRenderManager(force=false){if(!rm)return;if(state.project?.id!==rm.project){closeRenderManager();return;}const active=document.activeElement;if(!force&&renderManager.contains(active)&&active.matches('input:not([type=checkbox]),select'))return;
  const scrollTop=renderManager.querySelector('.rmBody')?.scrollTop||0;const targets=managerTargets(),root=state.project.nodes.find(n=>n.id===rm.scope);renderManager.replaceChildren();
  const head=el('div',undefined,'rmHead');head.append(el('strong','Rendering'),muted(root?.name||(rm.nodeIds?'Selected targets':'Project outputs')),button('Back to graph',closeRenderManager));renderManager.append(head);
  const scope=el('select');scope.setAttribute('aria-label','Render scope');for(const f of [{id:'',name:'All project outputs'},...state.project.nodes.filter(n=>n.type==='folder'&&folderHasRendering(n)||n.type==='render'&&(n.render_plan.folder_id||(state.project.renders||[]).some(r=>r.operation_id===n.id&&r.status!=='Deleted')))]){const o=el('option',f.name+(f.id?' · '+outputTargets(f.id).length+' targets':''));o.value=f.id;scope.append(o);}scope.value=rm.scope||'';scope.title='Choose an output folder or Render node to manage.';scope.onchange=()=>{rm.scope=scope.value||null;rm.nodeIds=null;rm.checked=new Set(outputTargets(rm.scope).map(n=>n.id));rm.draft={...(state.project.nodes.find(n=>n.id===rm.scope)?.render_overrides||(rm.scope?{}:state.project.render_overrides)||{})};paintRenderManager(true);};
  const scopebar=el('div',undefined,'rmScopebar');scopebar.append(el('label','Output scope'),scope);renderManager.append(scopebar);
  const tabbar=el('div',undefined,'rmTabbar'),tabs=el('div',undefined,'rmTabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Rendering views');for(const [key,label] of [['targets','Targets'],['queue','Render queue'],['versions','Versions']]){const b=button(label,()=>{rm.tab=key;paintRenderManager();});b.classList.toggle('active',rm.tab===key);b.setAttribute('role','tab');b.id='rm-tab-'+key;b.setAttribute('aria-selected',String(rm.tab===key));b.setAttribute('aria-controls','rm-panel');b.tabIndex=rm.tab===key?0:-1;const count=key==='targets'?targets.length:key==='versions'?scopeRuns().length:(state.project.render_queue||[]).filter(q=>['Queued','Preparing','Rendering'].includes(q.status)&&queueInScope(q,targets)).length;b.append(el('span',String(count),'rmTabCount'));b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const keys=['targets','queue','versions'],i=keys.indexOf(key);rm.tab=keys[e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:-1)+3)%3];paintRenderManager();$('rm-tab-'+rm.tab).focus();};tabs.append(b);}tabbar.append(tabs);renderManager.append(tabbar);if(rm.notice)renderManager.append(el('p',rm.notice,'rmNotice'));
  const body=el('div',undefined,'rmBody');body.id='rm-panel';body.setAttribute('role','tabpanel');body.setAttribute('aria-labelledby','rm-tab-'+rm.tab);renderManager.append(body);
  if(rm.tab==='targets'){
    const left=el('div',undefined,'rmTargets'),right=el('div',undefined,'rmOverrides');body.append(left);const batchPanel=renderPanel('Batch overrides','workspace-batch:'+rm.scope,rm.settingsOpen);batchPanel.classList.add('rmBatchOverrides');batchPanel.append(right);
    const summary=el('div',undefined,'rmOverrideSummary');if(Object.keys(rm.draft).length){summary.append(el('span','Batch changes:'));for(const [key,value] of Object.entries(rm.draft)){const label=renderSettings.find(s=>s[0]===key)?.[1]||key;summary.append(badge(key==='advanced'?'Blender settings · '+Object.keys(value).length:label+' → '+value));}summary.append(button('Reset',()=>{rm.draft={};paintRenderManager();}));}else summary.hidden=true;left.append(summary,batchPanel);
    const selectAll=el('input');selectAll.type='checkbox';selectAll.checked=targets.length>0&&targets.every(n=>rm.checked.has(n.id));selectAll.setAttribute('aria-label','Select all render targets');selectAll.onchange=()=>{rm.checked=selectAll.checked?new Set(targets.map(n=>n.id)):new Set();paintRenderManager();};const title=el('label','Select all');title.prepend(selectAll);left.append(title);
    rm.editors=connectedRenderEditors(left,targets,'workspace',{
      selection:{has:(t,owner)=>rm.checked.has(targetKey(t,owner)),change:(t,checked,owner)=>{checked?rm.checked.add(targetKey(t,owner)):rm.checked.delete(targetKey(t,owner));selectAll.checked=targets.every(n=>rm.checked.has(n.id));updateBatchButton();}},
      queueOverrides:()=>rm?.draft||{},versionLabel:()=>rm?.label||''
    });
    if(!targets.length)left.append(muted('Connect Blend files → Render → Folder to add render targets.'));
    function targetKey(t,owner){return owner?owner+':'+t.id:t.id;}
    right.title='Checked properties replace the selected setups’ settings. Other values stay per setup.';
    settingEditor(right,rm.draft,{},values=>{rm.draft={...values,...(rm.draft.advanced?{advanced:rm.draft.advanced}:{})};updateEffectiveRows();});const batchAdvanced=renderSettingsCatalogue(right,rm.draft.advanced,async()=>{const selected=targets.filter(n=>rm.checked.has(n.id)),catalogues=await Promise.all(selected.map(loadRenderSettings)),scenes=selected.map((n,i)=>catalogues[i][savedRender(n).name]||[]);return scenes.length?scenes[0].filter(e=>scenes.every(items=>items.some(x=>x.key===e.key&&x.type===e.type&&x.editable===e.editable&&x.array===e.array))):[];},'batch:'+rm.scope,()=>{const values=batchAdvanced.read();if(Object.keys(values).length)rm.draft.advanced=values;else delete rm.draft.advanced;updateEffectiveRows();});const batchToggle=batchPanel.ontoggle;batchPanel.ontoggle=()=>{batchToggle();rm.settingsOpen=batchPanel.open;};const label=el('input');label.placeholder='Optional version label · e.g. draft / final';label.value=rm.label;label.setAttribute('aria-label','Version label');label.oninput=()=>rm.label=label.value;right.append(label,actions(button('Save preset for this scope',()=>{const operation=state.project.nodes.find(n=>n.id===rm.scope&&n.type==='render');return operation?run('render_node_config',{node_id:operation.id,plan:{...(rm.editors.find(e=>e.root.dataset.renderOperationId===operation.id)?.read()||operation.render_plan),overrides:rm.draft}}):run('batch_settings',{folder_id:rm.scope,overrides:rm.draft});}),button('Clear overrides',()=>{rm.draft={};paintRenderManager();})));

    const footer=el('div',undefined,'rmFooter');const renderButton=button('',async()=>{const ids=targets.filter(n=>rm.checked.has(n.id)).map(n=>n.id),submission={project:rm.project,scope:rm.scope,overrides:structuredClone(rm.draft),label:rm.label};if(!ids.length||!await saveRenderEditors(rm.editors||[])||state.project?.id!==submission.project)return;const result=await run('queue_batch',{folder_id:state.project.nodes.some(n=>n.id===submission.scope&&n.type==='render')?null:submission.scope,node_ids:ids,overrides:submission.overrides,label:submission.label});if(result&&rm){rm.tab='queue';paintRenderManager();}});renderButton.id='rmQueueBatch';footer.append(muted('Renders one file at a time. Every run creates a new version.'),renderButton);renderManager.append(footer);updateBatchButton();
  }else if(rm.tab==='queue'){
    const groups=RenderOverview.batches(state.project,q=>queueInScope(q,targets)).reverse(),live=groups.filter(b=>b.active),finished=groups.filter(b=>!b.active);
    for(const batch of live){body.append(renderBatchCard(batch));const list=el('div',undefined,'renderQueueList');list.append(...batch.jobs.map(j=>renderQueueRow(j.q)));body.append(list);}
    const history=renderPanel('Finished batches · '+finished.length,'queue-history',!live.length);body.append(history);
    for(const batch of finished.slice(0,8)){const group=renderPanel((batch.label||'Batch')+' · '+batch.done+'/'+batch.jobs.length+' complete · '+batch.status,'batch:'+batch.id,false);group.append(renderBatchCard(batch,true),...batch.jobs.map(j=>renderQueueRow(j.q)));history.append(group);}
    if(finished.length>8)history.append(muted('Older runs are available in Versions.'));
    if(!groups.length)body.append(muted('No renders queued in this scope.'));
  }else paintVersionList(body);
  body.scrollTop=scrollTop;rm.signature=JSON.stringify([state.project.renders,state.project.render_queue,targets.map(n=>n.render_config)]);polishInterface();
}
function updateBatchButton(){const b=$('rmQueueBatch');if(b){const selected=managerTargets().filter(n=>rm.checked.has(n.id)),count=selected.length,invalid=selected.some(n=>!renderTargetReady(n,rm.draft));b.textContent='Render '+count+' target'+(count===1?'':'s');b.disabled=!count||invalid||window.pipelineBusy();b.title=invalid?'Choose saved scenes and cameras for the selected targets.':'Queue the selected saved scenes';}}
function versionDetails(r){modal('Render version · '+(r.name||'Render')+' · r'+String(r.number).padStart(3,'0'),[],()=>{});$('submit').textContent='Back';$('fields').append(renderRunEntry(r));}
function paintVersionList(body){
  const runs=scopeRuns(),tools=el('div',undefined,'rmVersionTools'),search=el('input'),sort=el('select'),list=el('div');search.placeholder='Find file, scene or version label';search.setAttribute('aria-label','Find render versions');search.value=rm.versionSearch;sort.setAttribute('aria-label','Sort render versions');for(const [value,label] of [['newest','Newest first'],['oldest','Oldest first'],['file','Group by file'],['size','Largest first']]){const o=el('option',label);o.value=value;sort.append(o);}sort.value=rm.versionSort;tools.append(search,sort);body.append(tools,list);
  function draw(){list.replaceChildren();const query=rm.versionSearch.trim().toLowerCase(),filtered=runs.filter(r=>[r.name,r.config?.scene,r.label,r.status,'r'+String(r.number).padStart(3,'0')].join(' ').toLowerCase().includes(query));filtered.sort((a,b)=>rm.versionSort==='oldest'?a.created.localeCompare(b.created):rm.versionSort==='file'?(a.name||'').localeCompare(b.name||'')||b.number-a.number:rm.versionSort==='size'?((b.size_bytes||0)+(b.input_bytes||0))-((a.size_bytes||0)+(a.input_bytes||0)):b.created.localeCompare(a.created));list.append(muted(`${filtered.length} of ${runs.length} versions · ${sizeLabel(runs.reduce((sum,r)=>sum+(r.size_bytes||0)+(r.input_bytes||0),0))} total, including render copies.`));const table=el('table',undefined,'rmTable rmVersionsTable'),head=el('tr');for(const label of ['File / setup','Version','Created','Status','Size',''])head.append(el('th',label));table.append(head);let group='';for(const r of filtered.slice(0,rm.versionLimit)){if(rm.versionSort==='file'&&group!==r.node_id){group=r.node_id;const row=el('tr',undefined,'rmVersionGroup'),cell=el('th',(r.name||'Render')+' · '+filtered.filter(i=>i.node_id===r.node_id).length+' versions');cell.colSpan=6;row.append(cell);table.append(row);}const row=el('tr'),file=el('td');file.append(el('strong',r.name||'Render'));if(r.config?.scene)file.append(muted(r.config.scene+' / '+(r.config.view_layer||'All enabled layers')));const version=el('td','r'+String(r.number).padStart(3,'0'));if(r.label)version.append(muted(r.label));const created=new Date(r.created),when=el('td',created.toLocaleDateString());when.append(muted(created.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})));const status=el('td');status.append(badge(r.status,r.status==='Complete'?'good':['Failed','Interrupted'].includes(r.status)?'danger':''));if(r.status==='Rendering')status.append(muted((r.progress||0)+'%'));if(r.dependency_warnings?.length){const warning=muted('Image warnings · '+r.dependency_warnings.length);warning.classList.add('renderImageWarnings');warning.title=r.dependency_warnings.map(w=>w.path+' · '+w.reason).join('\n');status.append(warning);}if(r.image_notices?.length)status.append(muted('Unused images · '+r.image_notices.length));const controls=el('td');controls.append(button('Open output',()=>run('render_open',{run_id:r.id})),button('Details',()=>versionDetails(r)));row.append(file,version,when,status,el('td',sizeLabel((r.size_bytes||0)+(r.input_bytes||0))),controls);table.append(row);}list.append(table);if(!filtered.length)list.append(muted(runs.length?'No versions match this search.':'Render a connected file to create its first version.'));if(filtered.length>rm.versionLimit)list.append(button('Show more versions',()=>{rm.versionLimit+=20;draw();}));}
  search.oninput=()=>{rm.versionSearch=search.value;rm.versionLimit=20;draw();};sort.onchange=()=>{rm.versionSort=sort.value;rm.versionLimit=20;draw();};draw();
}
function updateEffectiveRows(){// Preserve editor focus and update only the target table.
  const active=document.activeElement,grid=renderManager.querySelector('.rmOverrides');if(!grid)return;active.blur();const old=grid;paintRenderManager();const fresh=renderManager.querySelector('.rmOverrides');fresh.replaceWith(old);active.focus();
}
function runRetry(q){run('queue_render',{node_id:q.node_id,overrides:q.overrides||{},settings:q.settings,label:q.label||''});}
function deleteRenderVersion(r){modal('Permanently delete render version?',[],()=>run('render_delete',{run_id:r.id,confirmed:true}));$('fields').append(el('strong',`${r.name||'Render'} · r${String(r.number).padStart(3,'0')}`),muted(r.output),muted(`Deletes rendered files and frozen inputs (${sizeLabel((r.size_bytes||0)+(r.input_bytes||0))}). Working Blend Files and other versions are kept. This cannot be undone.`));$('submit').textContent='Delete version permanently';}
const priorRunEntry=renderRunEntry;renderRunEntry=function(r){const entry=el('div',undefined,'renderRun rmVersion');entry.append(actions(el('strong',`${r.name||state.project.nodes.find(n=>n.id===r.node_id)?.name||'Render'} · r${String(r.number).padStart(3,'0')}`),badge(r.status,r.status==='Complete'?'good':r.status==='Failed'?'danger':''),...(r.label?[badge(r.label)]:[])),muted(`${r.config?.scene||''} · ${new Date(r.created).toLocaleString()} · ${sizeLabel((r.size_bytes||0)+(r.input_bytes||0))} · ${r.image_count??r.file_count??'—'} images`),el('p',r.output,'uxPath'));
  if(r.status==='Deleted'){entry.append(muted('Deleted · revision number is reserved.'));return entry;}
  if(r.status==='Rendering'){const p=el('progress');p.max=100;if(r.progress)p.value=r.progress;entry.append(p,muted((r.phase||'Starting Blender')+(r.current_frame!=null?' · frame '+r.current_frame:'')));}
  if(r.render_device){const device=r.render_device;entry.append(muted(device.effective+(device.backend&&device.backend!=='NONE'?' · '+device.backend:'')+(device.devices?.length?' · '+device.devices.join(', '):'')));for(const warning of device.warnings||[])entry.append(el('p',warning,'warning'));}
  const controls=actions(button('Open output',()=>run('render_open',{run_id:r.id})));if(r.status==='Rendering')controls.append(button('Cancel',()=>run('render_cancel',{run_id:r.id})));entry.append(controls);
  if(r.compositor_outputs?.length){const outputs=el('details');outputs.append(el('summary','Compositor outputs · '+r.compositor_outputs.length));for(const pass of r.compositor_outputs)outputs.append(muted('compositor/'+pass.prefix+'#### · '+pass.format));entry.append(outputs);}
  if(r.error)entry.append(el('p',r.error,'warning'));
  const detail=el('details');detail.append(el('summary','Details / cleanup'));detail.append(muted(Object.keys(r.overrides||{}).length?'Batch overrides: '+JSON.stringify(r.overrides):'Per-scene settings · no batch overrides'),el('pre',JSON.stringify(r.actual_settings||r.config,null,2)),muted('Frozen inputs: '+Object.keys(r.input_hashes||{}).join(', ')));if(r.timing)detail.append(muted('Preparation '+(r.preparation_seconds??'—')+'s · Load / settings '+r.timing.load_seconds+'s · Blender render '+r.timing.render_seconds+'s'));if(r.detail)detail.append(el('pre',r.detail));if(!['Rendering','Preparing'].includes(r.status))detail.append(button('Delete version…',()=>deleteRenderVersion(r)));entry.append(detail);return entry;
};
PipelineUI.use('paintTasks','render-status',1500,function(next){next();const label='Rendering'+((state.project?.render_queue||[]).filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length?' · '+state.project.render_queue.filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length:'');if(activity.textContent.trim()!==label)activity.textContent=label;if(rm&&renderManager.open){const targets=managerTargets(),signature=JSON.stringify([state.project.renders,state.project.render_queue,targets.map(n=>n.render_config)]);if(signature!==rm.signature)paintRenderManager();updateBatchButton();}
  for(const n of state.project?.nodes||[]){const card=document.querySelector(`[data-id="${n.id}"]`);if(!card)continue;if(n.type==='folder'){const count=outputTargets(n.id).length;let b=card.querySelector('.rmFolderButton');if(!count&&!folderRuns(n).length){b?.remove();continue;}if(!b){b=button(count?'Rendering · '+count:'Render versions',()=>openRenderManager(n.id));b.classList.add('rmFolderButton');card.querySelector('.folderTools')?.append(b);}else if(b.textContent.trim()!==(count?'Rendering · '+count:'Render versions'))b.textContent=count?'Rendering · '+count:'Render versions';}else if(n.render_config&&!card.querySelector('.rmQuickRender')){const b=button('Render',()=>run('queue_render',{node_id:n.id}),'Queue this file using its own settings');b.classList.add('rmQuickRender');const output=card.querySelector('.renderOutput'),text=[...output.childNodes].find(c=>c.nodeType===Node.TEXT_NODE);if(text){const label=el('span',text.textContent,'rmOutputLabel');label.title=text.textContent;text.replaceWith(label);}output.prepend(b);}}
});
PipelineUI.use('render','render-actions',1501,function(next){next();paintTasks();});
const directRenderDrafts=new Map();
function renderFileEditor(n){
  const key=state.project.id+':'+n.id,base=JSON.stringify(n.render_config),draft=directRenderDrafts.get(key),config=draft?.base===base?draft.read():structuredClone(n.render_config||{}),{field,selectControl}=PipelineUI.graphNodes;
  if(draft?.base!==base)directRenderDrafts.delete(key);
  const form=el('form',undefined,'renderNodeForm renderEmbeddedEditor'),scenes=(n.scan?.scenes||[]).filter(s=>!s.linked),scene=selectControl('Scene for '+n.name,scenes.map(s=>({value:s.name,label:s.name})),config.scene),camera=selectControl('Camera for '+n.name,[],config.camera||''),settings=el('div'),options=renderPanel('Output options','direct-options:'+n.id,false),prefix=el('input'),auto=el('input'),saveButton=button('Save changes',()=>save()),pending=el('span','Unsaved changes','renderPending');
  form.dataset.renderFileId=n.id;prefix.value=config.prefix||'';prefix.setAttribute('aria-label','Filename prefix for '+n.name);auto.type='checkbox';auto.checked=config.auto_prefix??true;auto.setAttribute('aria-label','Automatic filename for '+n.name);
  let common,advanced={read:()=>config.advanced||{}};
  function read(){return {...config,scene:scene.value,camera:camera.value,auto_prefix:auto.checked,prefix:prefix.value,...Object.fromEntries(renderSettings.map(([k])=>[k,null])),...common.read(),advanced:advanced.read()};}
  function changed(){directRenderDrafts.set(key,{base,read});pending.hidden=false;}
  async function save(){if(!form.reportValidity())return null;const value=read();directRenderDrafts.delete(key);const result=await run('render_config',{node_id:n.id,...value});if(!result)directRenderDrafts.set(key,{base,read:()=>value});return result;}
  function paint(){const saved=scenes.find(s=>s.name===scene.value)||{};camera.replaceChildren();for(const c of ['',...(saved.cameras||[])]){const o=el('option',c||'Saved active camera');o.value=c;camera.append(o);}camera.value=config.camera||'';settings.replaceChildren();common=settingEditor(settings,config,saved,changed,'direct:'+n.id);advanced=renderSettingsCatalogue(settings,config.advanced,async()=>{const catalogue=await loadRenderSettings(n);return catalogue[scene.value]||[];},'direct:'+n.id+':'+scene.value,changed);}
  scene.onchange=()=>{Object.assign(config,read(),{scene:scene.value,camera:''});paint();};auto.onchange=()=>prefix.disabled=auto.checked;prefix.disabled=auto.checked;pending.hidden=!directRenderDrafts.has(key);
  options.append(field('Camera',camera),field('Automatic name',auto),field('Filename',prefix));form.append(field('Scene',scene),settings,options,actions(saveButton,pending));form.oninput=form.onchange=changed;form.onsubmit=e=>{e.preventDefault();save();};paint();return {root:form,save,dirty:()=>directRenderDrafts.has(key)};
}
function connectedRenderEditors(parent,targets,context='folder',options={}){
  const editors=[],operations=[...new Set(targets.map(t=>t.operation_id).filter(Boolean))];
  for(const id of operations){const operation=state.project.nodes.find(n=>n.id===id);if(!operation)continue;const group=operations.length>1?renderPanel(operation.name,'connected-operation:'+context+':'+id,true):el('div',undefined,'renderConnectedOperation');group.classList.add('renderConnectedOperation');if(operations.length===1)group.append(el('div','From '+operation.name,'renderConnectionOrigin'));const editor=window.pipelineRenderPlanEditor(operation,{context,...options,targetIds:context==='workspace'?targets.filter(t=>t.operation_id===id).map(t=>t.target_id):undefined});group.append(editor.root);parent.append(group);editors.push(editor);}
  for(const target of targets.filter(t=>!t.operation_id)){const group=renderPanel(target.name,'connected-file:'+context+':'+target.id,true);group.classList.add('renderConnectedOperation');const editor=renderFileEditor(target),summary=group.querySelector('summary');if(options.selection){const check=el('input');check.type='checkbox';check.checked=options.selection.has(target);check.setAttribute('aria-label','Select '+target.name+' for batch');check.onclick=e=>e.stopPropagation();check.onchange=()=>options.selection.change(target,check.checked);summary.prepend(check);}summary.append(button('▶',async()=>{if(await editor.save())return run('queue_render',{node_id:target.id,overrides:options.queueOverrides?.()||{},label:options.versionLabel?.()||''});},'Save changes and render this file'));group.append(editor.root);parent.append(group);editors.push(editor);}
  return editors;
}
async function saveRenderEditors(editors){for(const editor of editors)if(editor.dirty()&&!await editor.save())return false;return true;}
function folderRenderDetails(pane,n){
  const projectId=state.project.id,targets=outputTargets(n.id),connected=renderPanel('Connected setups · '+targets.length,'folder-setups:'+n.id,true),editors=connectedRenderEditors(connected,targets),live=renderPanel('Render activity','folder-jobs:'+n.id,false);
  connected.classList.add('renderConnectedSetups');live.dataset.renderFolderJobs=n.id;
  const batches=RenderOverview.batches(state.project,q=>queueInFolder(q,n));for(const b of batches.filter(b=>b.active))live.append(renderBatchCard(b,true),...b.jobs.map(j=>renderQueueRow(j.q)));if(!batches.some(b=>b.active))live.append(muted('No active batch'));
  const controls=actions(button('Render all · '+targets.length,async()=>{if(await saveRenderEditors(editors)&&state.project?.id===projectId)return run('queue_batch',{folder_id:n.id,overrides:{}});},'Save pending setup changes and render this folder and its subfolders'),button('Queue & versions',()=>openRenderManager(n.id)));controls.classList.add('renderFolderControls');pane.append(controls,connected,live);
}
let folderRenderingTab=null;PipelineUI.use('inspect','render-details',1502,function(next){next();const n=state.project?.nodes.find(n=>n.id===selected);if(!n)return;
  if(n.type==='folder'&&folderHasRendering(n)){const pane=$('inspector'),tabs=folderDetailTabs(n);pane.querySelector('.uxInspectorHeading')?.after(tabs);if(folderRenderingTab?.id===n.id&&folderRenderingTab.key==='render'){for(const c of [...pane.children])if(c!==tabs&&!c.classList.contains('uxInspectorHeading'))c.remove();folderRenderDetails(pane,n);}}
  if(n.type==='blend'&&inspectorTab==='render'){const content=$('inspector').querySelector('.uxTabContent');if(content){
    content.replaceChildren();
    if(n.render_config){
      const projectId=state.project.id,editor=renderFileEditor(n),controls=actions(button('Render',async()=>{if(await saveRenderEditors([editor])&&state.project?.id===projectId)return run('queue_render',{node_id:n.id});}),button('Queue & versions',()=>openRenderManager(null,[n.id])));
      content.append(muted('Output → '+(state.project.nodes.find(f=>f.id===n.render_config.folder_id)?.name||'Missing folder')),controls,editor.root);
    }else content.append(muted('Drag the blue socket to a Render node or Folder to set up rendering.'));
    const versions=renderPanel('Versions','file-versions:'+n.id,false);versions.append(...(state.project.renders||[]).filter(r=>r.node_id===n.id&&r.status!=='Deleted').slice().reverse().map(renderRunEntry));content.append(versions);
  }}
});
updateQueueCount=function(){const count=(state.project?.render_queue||[]).filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length;activity.textContent='Rendering'+(count?' · '+count:'');};
activity.onclick=()=>{if(busy)return;if(renderManager.open)closeRenderManager();else openRenderManager();};
queueSelection=function(){openRenderManager(null,[...selection]);};for(const b of viewList.querySelectorAll('button'))if(b.textContent.includes('Queue selected'))b.onclick=queueSelection;
PipelineUI.use('run','render-feedback',1503,async function(next, action,args={}){const before=new Set((state.jobs||[]).map(j=>j.id)),result=await next(action,args);if(['queue_render','queue_batch','render_config','batch_settings','render_delete'].includes(action)){const failure=result?.jobs?.find(j=>!before.has(j.id)&&j.action===action&&j.status==='Failed');if(failure?.error_code==='render_image_warnings')return result;if(failure||!result){if(rm){rm.notice=failure?.error||$('toast').textContent||'Operation failed. Check project details.';paintRenderManager();}return null;}if(rm&&action==='batch_settings'){rm.notice='Batch settings saved for this folder scope.';paintRenderManager();}}return result;});
if(state.project)render();
