/* Render targets are explicit blue output connections, never folder membership. */
const renderSettings=[['width','Width','number'],['height','Height','number'],['percentage','Scale %','number'],['samples','Samples','number'],['start','First frame','number'],['end','Last frame','number'],['engine','Engine',[['CYCLES','Cycles'],['BLENDER_EEVEE','EEVEE']]],['format','Format',[['PNG','PNG'],['OPEN_EXR','OpenEXR'],['OPEN_EXR_MULTILAYER','Multilayer EXR'],['JPEG','JPEG'],['FFMPEG','Video (saved encoding)']]],['denoise','Cycles denoising',[[true,'On'],[false,'Off']]]];
function outputTargets(folderId=null){const all=state.project?.nodes||[],root=all.find(n=>n.id===folderId),allowed=new Set(all.filter(n=>n.type==='folder'&&(!root||n.id===root.id||inFrame(n,root.id)||n.path.startsWith(root.path+'/'))).map(n=>n.id));return all.filter(n=>n.type==='blend'&&!n.external&&allowed.has(n.render_config?.folder_id));}
folderRuns=function(n){return [...(state.project?.renders||[])].reverse().filter(r=>r.status!=='Deleted'&&(r.output===n.path||r.output.startsWith(n.path+'/')));};
function folderHasRendering(n){return outputTargets(n.id).length>0||folderRuns(n).length>0;}
function savedRender(n){return n.scan?.scenes?.find(s=>s.name===n.render_config?.scene)||n.scan?.scenes?.find(s=>!s.linked)||{};}
function effectiveSettings(n,overrides={}){const saved=savedRender(n),config=n.render_config||{},values={...saved};for(const [k,v] of Object.entries(config))if(v!==null&&v!==undefined)values[k]=v;return {...values,...overrides};}
function sizeLabel(bytes){return bytes>=1073741824?(bytes/1073741824).toFixed(1)+' GB':bytes>=1048576?(bytes/1048576).toFixed(1)+' MB':Math.ceil((bytes||0)/1024)+' KB';}
function settingEditor(parent,initial={},saved={},onchange=()=>{}){
  const grid=el('div',undefined,'rmSettingsWrap'),main=el('div',undefined,'rmSettings'),advanced=el('details',undefined,'rmAdvanced'),extra=el('div',undefined,'rmSettings'),controls=new Map();advanced.append(el('summary','Frames / engine / format / denoising'),extra);advanced.open=['start','end','engine','format','denoise'].some(k=>initial[k]!=null);grid.append(main,advanced);parent.append(grid);
  for(const [key,label,type] of renderSettings){const row=el('div',undefined,'rmSetting'),check=el('input');check.type='checkbox';check.checked=initial[key]!==null&&initial[key]!==undefined;check.setAttribute('aria-label','Override '+label);const title=el('label',label);title.prepend(check);const input=el(Array.isArray(type)?'select':'input');input.setAttribute('aria-label',label);if(Array.isArray(type)){for(const [value,text] of type){const o=el('option',text);o.value=String(value);input.append(o);}}else {input.type=type;input.step='1';if(!['start','end'].includes(key))input.min='1';}
    const fallback=key==='samples'?64:key==='percentage'?100:key==='engine'?'CYCLES':key==='format'?'PNG':key==='denoise'?true:key==='width'?1920:key==='height'?1080:key==='start'?1:250;
    const inherited=Object.keys(saved).length?'Saved in Blender':'Per scene';input.value=String(initial[key]??saved[key]??(check.checked?fallback:''));input.placeholder='Per scene';input.disabled=!check.checked;check.title='Enable to change '+label+'; uncheck to use the saved scene setting.';const hint=el('small',check.checked?'Override':inherited,'rmOrigin');row.append(title,input,hint);(['start','end','engine','format','denoise'].includes(key)?extra:main).append(row);controls.set(key,{check,input});
    check.onchange=()=>{input.disabled=!check.checked;if(check.checked&&!input.value)input.value=String(fallback);hint.textContent=check.checked?'Override':inherited;row.classList.toggle('enabled',check.checked);onchange(read());};input.oninput=()=>onchange(read());row.classList.toggle('enabled',check.checked);
  }
  function read(){const values={};for(const [key,{check,input}] of controls)if(check.checked)values[key]=key==='denoise'?input.value==='true':['engine','format'].includes(key)?input.value:Number(input.value);return values;}
  return {read,reset(){for(const {check,input} of controls.values()){check.checked=false;input.disabled=true;check.onchange();}},grid};
}
const renderCatalogCache=new Map();async function loadRenderSettings(n){const key=[state.project.id,n.id,n.scan?.hash,n.scan?.scanned_at].join(':');if(renderCatalogCache.has(key))return renderCatalogCache.get(key);const result=await api('read_render_settings',{node_id:n.id});if(renderCatalogCache.size>=30)renderCatalogCache.clear();renderCatalogCache.set(key,result.scenes);return result.scenes;}
configureRender=async function(n,folderId){
  let catalogue;try{catalogue=await loadRenderSettings(n);}catch(e){return error(e);}const scenes=(n.scan?.scenes||[]).filter(s=>!s.linked).map(s=>({...s,advanced_settings:catalogue[s.name]||[]})),config=n.render_config||{},scene=scenes.find(s=>s.name===config.scene)||scenes.find(s=>s.camera)||scenes[0];if(!scene)return error('Refresh this file to read its saved scenes.');const options=folders().filter(f=>f.value);if(!options.length)return error('Drag the blue output socket onto empty canvas to create an output folder.');
  let editor,advancedEditor;
  modal('Render settings · '+n.name,[{key:'folder_id',label:'Output folder',type:'select',options,value:folderId||config.folder_id||options[0].value},{key:'scene',label:'Scene',type:'select',options:scenes.map(s=>({label:s.name,value:s.name})),value:scene.name},{key:'camera',label:'Camera',type:'select',options:[{label:'Saved active camera',value:''},...scene.cameras.map(c=>({label:c,value:c}))],value:config.camera||''},{key:'auto_prefix',label:'Automatic date + scene filename',type:'checkbox',value:config.auto_prefix??true},{key:'prefix',label:'Filename prefix',value:config.prefix||renderPrefix(scene.name)}],v=>{
    delete v[''];const values=Object.fromEntries(renderSettings.map(([key])=>[key,null]));Object.assign(values,editor.read());run('render_config',{node_id:n.id,...v,...values,advanced:advancedEditor.read()});
  });
  $('fields').append(muted('Unchecked settings inherit the saved Blender scene. Render jobs change frozen copies; your working file keeps its settings and passes.'));
  editor=settingEditor($('fields'),config,scene);$('submit').textContent='Save settings';
  advancedEditor=advancedSettingsEditor($('fields'),scene,config.advanced||{});
  const prefix=()=>{$('field-prefix').readOnly=$('field-auto_prefix').checked;if($('field-auto_prefix').checked)$('field-prefix').value=renderPrefix($('field-scene').value);};$('field-auto_prefix').onchange=prefix;prefix();
  $('field-scene').onchange=()=>{const s=scenes.find(s=>s.name===$('field-scene').value);$('field-camera').replaceChildren();for(const c of ['',...s.cameras]){const o=el('option',c||'Saved active camera');o.value=c;$('field-camera').append(o);}editor.grid.remove();editor=settingEditor($('fields'),{},s);advancedEditor.root.remove();advancedEditor=advancedSettingsEditor($('fields'),s,{});prefix();};
};
window.pipelineCreateRenderFolder=function(n,p){const scene=savedRender(n),existing=new Set(state.project.nodes.filter(f=>f.type==='folder').map(f=>f.path));let title='Out_'+(scene.name||n.name),count=2;while(existing.has(title))title='Out_'+(scene.name||n.name)+'_'+count++;
  modal('Create an output folder here?',[{key:'title',label:'Folder name',value:title,required:true}],async v=>{const before=new Set(state.project.nodes.map(n=>n.id)),next=await run('folder',{title:v.title,...p,width:350,height:240});if(!next)return;const folder=next.project.nodes.find(f=>!before.has(f.id));if(!folder)return;const s=savedRender(n);if(!s.camera)return configureRender(n,folder.id);const config=n.render_config||{scene:s.name,camera:'',start:null,end:null,percentage:null,auto_prefix:true};const result=await run('render_config',{node_id:n.id,...config,folder_id:folder.id});if(result)status('Output connected · click Render on the file, or Rendering on its folder.');});$('fields').append(muted('Creates a regular folder with an explicit output connection. Each render gets a separate numbered version.'));$('submit').textContent='Create + connect';
};

const renderManager=el('dialog');renderManager.id='renderManager';document.body.append(renderManager);let rm=null;
function syncRenderingToggle(){const open=renderManager.open;activity.classList.toggle('active',open);activity.setAttribute('aria-pressed',String(open));activity.title=open?'Return to graph':'Render targets, batch overrides, queue and versions';document.body.classList.toggle('renderWorkspace',open);}
function closeRenderManager(){renderManager.close();syncRenderingToggle();}
renderManager.setAttribute('aria-label','Rendering workspace');activity.setAttribute('aria-controls','renderManager');syncRenderingToggle();renderManager.addEventListener('close',()=>{if(renderManager.open)return;rm=null;syncRenderingToggle();activity.focus();});
function openRenderManager(scope=null,nodeIds=null){if(!state.project)return;const target=state.project.nodes.find(n=>n.id===scope),initial=scope?(target?.render_overrides||{}):(state.project.render_overrides||{});rm={project:state.project.id,scope,nodeIds,tab:'targets',checked:new Set((nodeIds?outputTargets(scope).filter(n=>nodeIds.includes(n.id)):outputTargets(scope)).map(n=>n.id)),draft:{...initial},label:'',notice:'',settingsOpen:false,versionLimit:20,versionSearch:'',versionSort:'newest',signature:''};document.body.classList.add('renderWorkspace');paintRenderManager();if(!renderManager.open)renderManager.show();syncRenderingToggle();}
const renderFocusNode=focusNode;focusNode=function(n){if(renderManager.open)closeRenderManager();renderFocusNode(n);};
const renderPlaceFile=startPlacement;startPlacement=function(...args){if(renderManager.open)closeRenderManager();return renderPlaceFile(...args);};
const renderCreateFolder=createFolderHere;createFolderHere=function(...args){if(renderManager.open)closeRenderManager();return renderCreateFolder(...args);};
function managerTargets(){return outputTargets(rm.scope).filter(n=>!rm.nodeIds||rm.nodeIds.includes(n.id));}
function scopeRuns(){const scope=state.project.nodes.find(n=>n.id===rm.scope),ids=new Set(managerTargets().map(n=>n.id)),folders=state.project.nodes.filter(n=>n.type==='folder'&&(!scope||n.id===scope.id||inFrame(n,scope.id)||n.path.startsWith(scope.path+'/')));return [...(state.project.renders||[])].reverse().filter(r=>r.status!=='Deleted'&&(!rm.scope&&!rm.nodeIds||rm.nodeIds&&ids.has(r.node_id)||rm.scope&&folders.some(f=>r.output.startsWith(f.path+'/'))));}
function paintRenderManager(force=false){if(!rm)return;if(state.project?.id!==rm.project){closeRenderManager();return;}const active=document.activeElement;if(!force&&renderManager.contains(active)&&active.matches('input:not([type=checkbox]),select'))return;
  const targets=managerTargets(),root=state.project.nodes.find(n=>n.id===rm.scope);renderManager.replaceChildren();
  const head=el('div',undefined,'rmHead');head.append(el('strong','Rendering'),muted(root?.name||(rm.nodeIds?'Selected files':'Project outputs')),button('Back to graph',closeRenderManager));renderManager.append(head);
  const scope=el('select');scope.setAttribute('aria-label','Render scope');for(const f of [{id:'',name:'All project outputs'},...state.project.nodes.filter(n=>n.type==='folder'&&folderHasRendering(n))]){const o=el('option',f.name+(f.id?' · '+outputTargets(f.id).length+' targets':''));o.value=f.id;scope.append(o);}scope.value=rm.scope||'';scope.title='Choose which connected output folder tree to manage.';scope.onchange=()=>{rm.scope=scope.value||null;rm.nodeIds=null;rm.checked=new Set(outputTargets(rm.scope).map(n=>n.id));rm.draft={...(state.project.nodes.find(n=>n.id===rm.scope)?.render_overrides||(rm.scope?{}:state.project.render_overrides)||{})};paintRenderManager(true);};
  const scopebar=el('div',undefined,'rmScopebar');scopebar.append(el('label','Output scope'),scope);renderManager.append(scopebar);
  const tabbar=el('div',undefined,'rmTabbar'),tabs=el('div',undefined,'rmTabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Rendering views');for(const [key,label] of [['targets','Targets'],['queue','Render queue'],['versions','Versions']]){const b=button(label,()=>{rm.tab=key;paintRenderManager();});b.classList.toggle('active',rm.tab===key);b.setAttribute('role','tab');b.id='rm-tab-'+key;b.setAttribute('aria-selected',String(rm.tab===key));b.setAttribute('aria-controls','rm-panel');b.tabIndex=rm.tab===key?0:-1;const count=key==='targets'?targets.length:key==='versions'?scopeRuns().length:(state.project.render_queue||[]).filter(q=>['Queued','Preparing','Rendering'].includes(q.status)&&(!rm.scope&&!rm.nodeIds||targets.some(n=>n.id===q.node_id))).length;b.append(el('span',String(count),'rmTabCount'));b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const keys=['targets','queue','versions'],i=keys.indexOf(key);rm.tab=keys[e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:-1)+3)%3];paintRenderManager();$('rm-tab-'+rm.tab).focus();};tabs.append(b);}tabbar.append(tabs);if(rm.tab==='targets'&&targets.length){const toggle=button(rm.settingsOpen?'Hide batch settings':'Batch settings',()=>{rm.settingsOpen=!rm.settingsOpen;paintRenderManager();});toggle.className='rmSettingsToggle';toggle.setAttribute('aria-expanded',String(rm.settingsOpen));tabbar.append(toggle);}renderManager.append(tabbar);if(rm.notice)renderManager.append(el('p',rm.notice,'rmNotice'));
  const body=el('div',undefined,'rmBody');body.id='rm-panel';body.setAttribute('role','tabpanel');body.setAttribute('aria-labelledby','rm-tab-'+rm.tab);renderManager.append(body);
  if(rm.tab==='targets'){
    const left=el('div',undefined,'rmTargets'),right=el('div',undefined,'rmOverrides');body.classList.toggle('rmSplit',rm.settingsOpen);body.append(left);if(rm.settingsOpen)body.append(right);
    const summary=el('div',undefined,'rmOverrideSummary');if(Object.keys(rm.draft).length){summary.append(el('span','Batch changes:'));for(const [key,value] of Object.entries(rm.draft)){const label=renderSettings.find(s=>s[0]===key)?.[1]||key;summary.append(badge(key==='advanced'?'Advanced settings · '+Object.keys(value).length:label+' → '+value));}if(rm.draft.advanced)summary.append(button('Review advanced changes',advancedBatchSettings));summary.append(button('Reset',()=>{rm.draft={};paintRenderManager();}));}else summary.append(muted('Each file uses its own scene settings. Use Batch settings to change them together.'));left.append(summary);
    const selectAll=el('input');selectAll.type='checkbox';selectAll.checked=targets.length>0&&targets.every(n=>rm.checked.has(n.id));selectAll.setAttribute('aria-label','Select all render targets');selectAll.onchange=()=>{rm.checked=selectAll.checked?new Set(targets.map(n=>n.id)):new Set();paintRenderManager();};const title=el('label','Select all');title.prepend(selectAll);left.append(title);
    const table=el('table');table.className='rmTable';const header=el('tr');for(const text of ['File / scene','Resolution','Samples','Frames',''])header.append(el('th',text));table.append(header);
    for(const n of targets){const row=el('tr'),cell=el('td'),check=el('input');check.type='checkbox';check.checked=rm.checked.has(n.id);check.setAttribute('aria-label','Render '+n.name);check.onchange=()=>{check.checked?rm.checked.add(n.id):rm.checked.delete(n.id);updateBatchButton();};const label=el('label',n.name);label.prepend(check);cell.append(label);if(n.render_config.scene!==n.name)cell.append(muted(n.render_config.scene));const output=state.project.nodes.find(f=>f.id===n.render_config.folder_id),destination=muted('→ '+(output?.name||'Missing folder'));destination.title=output?.path||'';cell.append(destination);const advancedCount=Object.keys(n.render_config.advanced||{}).length;if(advancedCount)cell.append(muted(advancedCount+' advanced scene change'+(advancedCount===1?'':'s')));row.append(cell);
      const effective=effectiveSettings(n,rm.draft),base=effectiveSettings(n);for(const [keys,text,original] of [[['width','height','percentage'],`${effective.width} × ${effective.height} · ${effective.percentage??100}%`,`${base.width} × ${base.height} · ${base.percentage??100}%`],[['samples'],effective.samples??'Saved',base.samples??'Saved'],[['start','end'],`${effective.start}–${effective.end}`,`${base.start}–${base.end}`]]){const td=el('td',String(text));if(keys.some(k=>k in rm.draft))td.append(el('small','Batch override','rmOverrideTag'),el('small','Base: '+original,'rmBase'));else if(keys.some(k=>n.render_config[k]!=null))td.append(el('small','Scene setting','rmBase'));row.append(td);}const edit=el('td');edit.append(button('Settings',()=>configureRender(n)),button('Render',()=>run('queue_render',{node_id:n.id,overrides:rm.draft,label:rm.label}),'Render this file with the settings shown in this table'));row.append(edit);table.append(row);
    }left.append(table);if(!targets.length)left.append(muted('Connect a Blend File’s blue output socket to a folder to add a render target.'));
    right.append(el('strong','Batch overrides'),muted('Enable only the properties to replace across selected targets. Other settings, passes and encoding stay per scene.'));
    settingEditor(right,rm.draft,{},values=>{rm.draft={...values,...(rm.draft.advanced?{advanced:rm.draft.advanced}:{})};updateEffectiveRows();});right.append(button('All Blender render settings',advancedBatchSettings));const label=el('input');label.placeholder='Optional version label · e.g. draft / final';label.value=rm.label;label.setAttribute('aria-label','Version label');label.oninput=()=>rm.label=label.value;right.append(label,actions(button('Save preset for this scope',()=>run('batch_settings',{folder_id:rm.scope,overrides:rm.draft})),button('Clear overrides',()=>{rm.draft={};paintRenderManager();})));
    right.append(muted('Enabled values apply to every selected file. Unchecked values stay as set in each scene.'));
    const footer=el('div',undefined,'rmFooter');const renderButton=button('',async()=>{const ids=targets.filter(n=>rm.checked.has(n.id)).map(n=>n.id);if(!ids.length)return;const result=await run('queue_batch',{folder_id:rm.scope,node_ids:ids,overrides:rm.draft,label:rm.label});if(result&&rm){rm.tab='queue';paintRenderManager();}});renderButton.id='rmQueueBatch';footer.append(muted('Renders one file at a time. Every run creates a new version.'),renderButton);renderManager.append(footer);updateBatchButton();
  }else if(rm.tab==='queue'){
    const ids=new Set(targets.map(n=>n.id)),items=[...(state.project.render_queue||[])].filter(q=>!rm.scope&&!rm.nodeIds||ids.has(q.node_id));const pending=items.filter(q=>['Queued','Preparing','Rendering'].includes(q.status)),completed=items.filter(q=>!pending.includes(q)).reverse();items.splice(0,items.length,...pending,...completed.slice(0,5));body.append(muted('Files render in order. Cancelling keeps any finished frames.'));if(completed.length>5){const more=el('details',undefined,'rmEarlierJobs');more.append(el('summary','Earlier jobs · '+(completed.length-5)));for(const q of completed.slice(5))more.append(queueEntry(q));body.append(more);}
    for(const q of items){const entry=queueEntry(q);entry.append(muted((q.label?q.label+' · ':'')+(q.settings?.scene||'')+' · '+(Object.keys(q.overrides||{}).length?'Overrides: '+Object.keys(q.overrides).join(', '):'Per-scene settings')));const run=state.project.renders?.find(r=>r.id===q.run_id);if(run?.status==='Rendering'){const p=el('progress');p.max=100;p.value=run.progress||0;entry.append(p,muted('Frame '+run.frame+' · '+run.progress+'%'));}if(['Failed','Cancelled','Interrupted'].includes(q.status))entry.append(button('Retry same settings',()=>runRetry(q)));body.append(entry);}if(!items.length)body.append(muted('No renders queued in this scope.'));
  }else paintVersionList(body);
  rm.signature=JSON.stringify([state.project.renders,state.project.render_queue,targets.map(n=>n.render_config)]);polishInterface();
}
function updateBatchButton(){const b=$('rmQueueBatch');if(b){const count=managerTargets().filter(n=>rm.checked.has(n.id)).length;b.textContent='Render '+count+' file'+(count===1?'':'s');b.disabled=!count||window.pipelineBusy();}}
async function advancedBatchSettings(){if(!rm)return;const selected=managerTargets().filter(n=>rm.checked.has(n.id));if(!selected.length)return error('Select render targets first.');let catalogues;try{catalogues=await Promise.all(selected.map(loadRenderSettings));}catch(e){return error(e);}if(!rm)return;const scenes=selected.map((n,i)=>({...savedRender(n),advanced_settings:catalogues[i][savedRender(n).name]||[]})),entries=(scenes[0].advanced_settings||[]).filter(e=>scenes.every(s=>s.advanced_settings?.some(other=>other.key===e.key&&other.type===e.type&&other.array===e.array&&other.editable===e.editable)));let editor;modal('Advanced batch settings',[],()=>{if(!rm)return;const values=editor.read();if(Object.keys(values).length)rm.draft.advanced=values;else delete rm.draft.advanced;paintRenderManager();});$('fields').append(muted(`Changes apply to ${selected.length} selected files. Unchecked settings keep each scene’s saved values. Only settings present in every selected scene are listed. Values shown before enabling are from the first scene; common controls are managed in the batch panel.`));editor=advancedSettingsEditor($('fields'),{advanced_settings:entries},rm.draft.advanced||{});editor.root.open=true;$('submit').textContent='Apply batch changes';}
function versionDetails(r){modal('Render version · '+(r.name||'Render')+' · r'+String(r.number).padStart(3,'0'),[],()=>{});$('submit').textContent='Back';$('fields').append(renderRunEntry(r));}
function paintVersionList(body){
  const runs=scopeRuns(),tools=el('div',undefined,'rmVersionTools'),search=el('input'),sort=el('select'),list=el('div');search.placeholder='Find file, scene or version label';search.setAttribute('aria-label','Find render versions');search.value=rm.versionSearch;sort.setAttribute('aria-label','Sort render versions');for(const [value,label] of [['newest','Newest first'],['oldest','Oldest first'],['file','Group by file'],['size','Largest first']]){const o=el('option',label);o.value=value;sort.append(o);}sort.value=rm.versionSort;tools.append(search,sort);body.append(tools,list);
  function draw(){list.replaceChildren();const query=rm.versionSearch.trim().toLowerCase(),filtered=runs.filter(r=>[r.name,r.config?.scene,r.label,r.status,'r'+String(r.number).padStart(3,'0')].join(' ').toLowerCase().includes(query));filtered.sort((a,b)=>rm.versionSort==='oldest'?a.created.localeCompare(b.created):rm.versionSort==='file'?(a.name||'').localeCompare(b.name||'')||b.number-a.number:rm.versionSort==='size'?((b.size_bytes||0)+(b.input_bytes||0))-((a.size_bytes||0)+(a.input_bytes||0)):b.created.localeCompare(a.created));list.append(muted(`${filtered.length} of ${runs.length} versions · ${sizeLabel(runs.reduce((sum,r)=>sum+(r.size_bytes||0)+(r.input_bytes||0),0))} total, including render copies.`));const table=el('table',undefined,'rmTable rmVersionsTable'),head=el('tr');for(const label of ['File / scene','Version','Created','Status','Size',''])head.append(el('th',label));table.append(head);let group='';for(const r of filtered.slice(0,rm.versionLimit)){if(rm.versionSort==='file'&&group!==r.node_id){group=r.node_id;const row=el('tr',undefined,'rmVersionGroup'),cell=el('th',(r.name||'Render')+' · '+filtered.filter(i=>i.node_id===r.node_id).length+' versions');cell.colSpan=6;row.append(cell);table.append(row);}const row=el('tr'),file=el('td');file.append(el('strong',r.name||'Render'));if(r.config?.scene&&r.config.scene!==r.name)file.append(muted(r.config.scene));const version=el('td','r'+String(r.number).padStart(3,'0'));if(r.label)version.append(muted(r.label));const created=new Date(r.created),when=el('td',created.toLocaleDateString());when.append(muted(created.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})));const status=el('td');status.append(badge(r.status,r.status==='Complete'?'good':['Failed','Interrupted'].includes(r.status)?'danger':''));if(r.status==='Rendering')status.append(muted((r.progress||0)+'%'));const controls=el('td');controls.append(button('Open output',()=>run('render_open',{run_id:r.id})),button('Details',()=>versionDetails(r)));row.append(file,version,when,status,el('td',sizeLabel((r.size_bytes||0)+(r.input_bytes||0))),controls);table.append(row);}list.append(table);if(!filtered.length)list.append(muted(runs.length?'No versions match this search.':'Render a connected file to create its first version.'));if(filtered.length>rm.versionLimit)list.append(button('Show more versions',()=>{rm.versionLimit+=20;draw();}));}
  search.oninput=()=>{rm.versionSearch=search.value;rm.versionLimit=20;draw();};sort.onchange=()=>{rm.versionSort=sort.value;rm.versionLimit=20;draw();};draw();
}
function updateEffectiveRows(){// Preserve editor focus and update only the target table.
  const active=document.activeElement,grid=renderManager.querySelector('.rmOverrides');if(!grid)return;active.blur();const old=grid;paintRenderManager();const fresh=renderManager.querySelector('.rmOverrides');fresh.replaceWith(old);active.focus();
}
function runRetry(q){run('queue_render',{node_id:q.node_id,overrides:q.overrides||{},settings:q.settings,label:q.label||''});}
function deleteRenderVersion(r){modal('Permanently delete render version?',[],()=>run('render_delete',{run_id:r.id,confirmed:true}));$('fields').append(el('strong',`${r.name||'Render'} · r${String(r.number).padStart(3,'0')}`),muted(r.output),muted(`Deletes rendered files and frozen inputs (${sizeLabel((r.size_bytes||0)+(r.input_bytes||0))}). Working Blend Files and other versions are kept. This cannot be undone.`));$('submit').textContent='Delete version permanently';}
const priorRunEntry=renderRunEntry;renderRunEntry=function(r){const entry=el('div',undefined,'renderRun rmVersion');entry.append(actions(el('strong',`${r.name||state.project.nodes.find(n=>n.id===r.node_id)?.name||'Render'} · r${String(r.number).padStart(3,'0')}`),badge(r.status,r.status==='Complete'?'good':r.status==='Failed'?'danger':''),...(r.label?[badge(r.label)]:[])),muted(`${r.config?.scene||''} · ${new Date(r.created).toLocaleString()} · ${sizeLabel((r.size_bytes||0)+(r.input_bytes||0))} · ${r.file_count??'—'} output files`),el('p',r.output,'uxPath'));
  if(r.status==='Deleted'){entry.append(muted('Deleted · revision number is reserved.'));return entry;}
  if(r.status==='Rendering'){const p=el('progress');p.max=100;p.value=r.progress||0;entry.append(p);}
  const controls=actions(button('Open output',()=>run('render_open',{run_id:r.id})));if(r.status==='Rendering')controls.append(button('Cancel',()=>run('render_cancel',{run_id:r.id})));entry.append(controls);
  if(r.compositor_outputs?.length){const outputs=el('details');outputs.append(el('summary','Compositor outputs · '+r.compositor_outputs.length));for(const pass of r.compositor_outputs)outputs.append(muted('compositor/'+pass.prefix+'#### · '+pass.format));entry.append(outputs);}
  if(r.error)entry.append(el('p',r.error,'warning'));
  const detail=el('details');detail.append(el('summary','Details / cleanup'));detail.append(muted(Object.keys(r.overrides||{}).length?'Batch overrides: '+JSON.stringify(r.overrides):'Per-scene settings · no batch overrides'),el('pre',JSON.stringify(r.actual_settings||r.config,null,2)),muted('Frozen inputs: '+Object.keys(r.input_hashes||{}).join(', ')));if(r.detail)detail.append(el('pre',r.detail));if(!['Rendering','Preparing'].includes(r.status))detail.append(button('Delete version…',()=>deleteRenderVersion(r)));entry.append(detail);return entry;
};
PipelineUI.use('paintTasks','render-status',1500,function(next){next();const label='Rendering'+((state.project?.render_queue||[]).filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length?' · '+state.project.render_queue.filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length:'');if(activity.textContent.trim()!==label)activity.textContent=label;if(rm&&renderManager.open){const targets=managerTargets(),signature=JSON.stringify([state.project.renders,state.project.render_queue,targets.map(n=>n.render_config)]);if(signature!==rm.signature)paintRenderManager();updateBatchButton();}
  for(const n of state.project?.nodes||[]){const card=document.querySelector(`[data-id="${n.id}"]`);if(!card)continue;if(n.type==='folder'){const count=outputTargets(n.id).length;let b=card.querySelector('.rmFolderButton');if(!count&&!folderRuns(n).length){b?.remove();const text=card.querySelector('.folderContents>span');const info=state.folder_info?.[n.id];if(text&&!info?.error&&!info?.missing)text.textContent=info?.entries?.[0]?.name||(info?.files?info.files+' files':'Empty folder');continue;}if(!b){b=button(count?'Rendering · '+count:'Render versions',()=>openRenderManager(n.id));b.classList.add('rmFolderButton');card.querySelector('.folderTools')?.append(b);}else if(b.textContent.trim()!==(count?'Rendering · '+count:'Render versions'))b.textContent=count?'Rendering · '+count:'Render versions';}else if(n.render_config&&!card.querySelector('.rmQuickRender')){const b=button('Render',()=>run('queue_render',{node_id:n.id}),'Queue this file using its own settings');b.classList.add('rmQuickRender');const output=card.querySelector('.renderOutput'),text=[...output.childNodes].find(c=>c.nodeType===Node.TEXT_NODE);if(text){const label=el('span',text.textContent,'rmOutputLabel');label.title=text.textContent;text.replaceWith(label);}output.prepend(b);}}
});
PipelineUI.use('render','render-actions',1501,function(next){next();paintTasks();});
let folderRenderingTab=null;PipelineUI.use('inspect','render-details',1502,function(next){next();const n=state.project?.nodes.find(n=>n.id===selected);if(!n)return;
  if(n.type==='folder'&&folderHasRendering(n)){const pane=$('inspector'),tabs=el('div',undefined,'uxTabs');for(const [key,label] of [['folder','Folder'],['render','Rendering']]){const b=button(label,()=>{folderRenderingTab={id:n.id,key};inspect();});b.classList.toggle('active',folderRenderingTab?.id===n.id&&folderRenderingTab.key===key||key==='folder'&&folderRenderingTab?.id!==n.id);tabs.append(b);}pane.querySelector('.uxInspectorHeading')?.after(tabs);if(folderRenderingTab?.id===n.id&&folderRenderingTab.key==='render'){for(const c of [...pane.children])if(c!==tabs&&!c.classList.contains('uxInspectorHeading'))c.remove();const targets=outputTargets(n.id);pane.append(section('Connected outputs',muted(`${targets.length} render targets in this folder and its subfolders. Grouped files without output connections are excluded.`),actions(button('Manage rendering',()=>openRenderManager(n.id)),button('Queue all · scene settings',()=>run('queue_batch',{folder_id:n.id,overrides:{}}))),...targets.map(t=>section(t.name,muted(t.render_config.scene+' → '+state.project.nodes.find(f=>f.id===t.render_config.folder_id)?.name),actions(button('Render',()=>run('queue_render',{node_id:t.id})),button('Settings',()=>configureRender(t)))))));}}
  if(n.type==='blend'&&inspectorTab==='render'){const content=$('inspector').querySelector('.uxTabContent');if(content){content.replaceChildren(section('Output connection',muted(n.render_config?`${n.render_config.scene} → ${state.project.nodes.find(f=>f.id===n.render_config.folder_id)?.name||'Missing folder'}`:'Drag the blue socket to a folder or empty canvas.'),actions(button('Settings',()=>configureRender(n)),button('Render',()=>n.render_config?run('queue_render',{node_id:n.id}):configureRender(n)),button('Render manager',()=>openRenderManager(null,[n.id])))),muted('Uses per-scene settings. Batch overrides apply only when you queue them in the render manager.'),...(state.project.renders||[]).filter(r=>r.node_id===n.id&&r.status!=='Deleted').slice().reverse().map(renderRunEntry));}}
});
const renderingNodeMenu=nodeMenu;nodeMenu=function(n,...args){renderingNodeMenu(n,...args);if(n.type==='folder'&&folderHasRendering(n))$('contextMenu').append(button('Manage rendering…',()=>openRenderManager(n.id)));else if(n.type==='blend'&&n.render_config)$('contextMenu').append(button('Render',()=>run('queue_render',{node_id:n.id})));};
updateQueueCount=function(){const count=(state.project?.render_queue||[]).filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length;activity.textContent='Rendering'+(count?' · '+count:'');};
activity.onclick=()=>{if(busy)return;if(renderManager.open)closeRenderManager();else openRenderManager();};
queueSelection=function(){openRenderManager(null,[...selection]);};for(const b of viewList.querySelectorAll('button'))if(b.textContent.includes('Queue selected'))b.onclick=queueSelection;
PipelineUI.use('run','render-feedback',1503,async function(next, action,args={}){const before=new Set((state.jobs||[]).map(j=>j.id)),result=await next(action,args);if(['queue_render','queue_batch','render_config','batch_settings','render_delete'].includes(action)){const failure=result?.jobs?.find(j=>!before.has(j.id)&&j.action===action&&j.status==='Failed');if(failure||!result){if(rm){rm.notice=failure?.error||$('toast').textContent||'Operation failed. Check project details.';paintRenderManager();}return null;}if(rm&&action==='batch_settings'){rm.notice='Batch settings saved for this folder scope.';paintRenderManager();}}return result;});
if(state.project)render();
