/* Named startup files and a predictable project default. */
function templateOptions(includeDefault=false){return [...(includeDefault?[{value:'default',label:'Project default'}]:[]),{value:'',label:'Factory empty'},...(state.project?.templates||[]).map(t=>({value:t.id,label:t.name}))];}
function templateManager(){
  if(!state.project)return error('Open a project first.');
  modal('Startup templates',[{key:'template_id',label:'Default for new files',type:'select',options:[{value:'',label:state.app_startup?'App default · '+state.app_startup.name:'App default · Factory empty'},{value:'__factory__',label:'Factory empty'},...(state.project.templates||[]).map(t=>({value:t.id,label:t.name}))],value:state.project.default_template||''}],v=>run('template_default',v));
  $('fields').append(muted('New files use this default without a naming prompt. Templates preserve saved scene settings and starter objects. Captures are independent copies included in project backups.'));
  const n=state.project.nodes.find(n=>n.id===selected&&n.type==='blend');
  $('fields').append(actions(button('Import saved .blend',()=>captureTemplate()),button('Save selected file as template',()=>n?captureTemplate(n):error('Select a Blend File first.'))));
  $('fields').append(actions(button('Set app startup file…',()=>modal('Default for all projects',[{key:'source',label:'Saved startup .blend file',required:true},{key:'title',label:'Name',value:'Startup',required:true}],v=>run('save_app_startup',v)))));$('fields').append(muted('App default: '+(state.app_startup?.name||'Factory empty')+'. Captured locally; new files receive independent copies. A named project default overrides it.'));for(const t of state.project.templates||[])$('fields').append(muted(t.name+' · '+t.path));
}
function captureTemplate(n){modal('Capture startup template',[{key:'title',label:'Template name',required:true},...(n?[]:[{key:'source',label:'Saved .blend path',required:true}]),{key:'make_default',label:'Use as project default',type:'checkbox',value:true}],v=>run('save_template',{...v,...(n?{node_id:n.id}:{})}));$('fields').append(muted('Save in Blender first. Pack textures and remove external library links for a portable, self-contained startup file. The source stays unchanged.'));}
projectList.append(button('Startup templates',templateManager));
controls.get('addBlend').onclick=e=>{if(e.shiftKey){const p=placement();modal('Create Blend File',[{key:'title',label:'File name (optional)'},folderField(),{key:'template_id',label:'Startup template',type:'select',options:templateOptions(true)}],v=>run('blend',{...v,title:v.title||null,folder_id:v.folder_id||null,template_id:v.template_id==='default'?null:v.template_id,...p}));}else{const n=state.project?.nodes.find(n=>n.id===selected);startPlacement(n?.type==='folder'?n.id:n?.group||null);}};

PipelineUI.use('inspect','startup-defaults',500,function(next){next();if(state.project&&!selected&&!selectedConnection&&!selectedDataConnection){const t=state.project.templates?.find(t=>t.id===state.project.default_template);$('inspector').append(section('New file defaults',muted(t?t.name:state.project.default_template==='__factory__'?'Factory empty':state.app_startup?'App default · '+state.app_startup.name:'Factory empty'),button('Manage startup templates',templateManager)));}});
