/* Render queue, preflight, project presets and workflow state. */

async function showPreflight(node_id){
  const next=await run('preflight_report',node_id?{node_id}:{}),job=next?.jobs?.filter(j=>j.action==='preflight_report').at(-1),report=job?.companion_result;
  if(!report)return;modal('Saved-file preflight',[],()=>{});$('submit').textContent='Done';$('fields').append(muted(report.errors.length?'Resolve these errors before portable backup or rendering.':'No dependency errors found.'));
  for(const message of report.errors)$('fields').append(el('p',message,'warning'));
  for(const message of report.warnings)$('fields').append(muted(message));if(!report.errors.length&&!report.warnings.length)$('fields').append(muted('Cameras, render configuration and dependency paths checked.'));
}
function queueSelection(){const selectedFiles=state.project?.nodes.filter(n=>n.type==='blend'&&selection.has(n.id))||[],ready=selectedFiles.filter(n=>n.render_config),missing=selectedFiles.filter(n=>!n.render_config);if(!ready.length)return error('Select files with render settings first.');modal('Queue '+ready.length+' render'+(ready.length===1?'':'s'),[],async()=>{for(const n of ready)await run('queue_render',{node_id:n.id});});$('fields').append(muted('Files render one at a time. Inputs are frozen when each run starts.\n'+ready.map(n=>n.name).join('\n')));if(missing.length)$('fields').append(muted('Not queued until configured: '+missing.map(n=>n.name).join(', ')));}
viewList.append(button('Queue selected files',queueSelection));projectList.append(button('Project preflight',()=>showPreflight()));addList.append(button('Blend File from template',()=>controls.get('addBlend').onclick({shiftKey:true})));
controls.get('newProject').onclick=()=>modal('New local project',[{key:'parent',label:'Parent folder',required:true},{key:'title',label:'Project name',required:true},{key:'preset',label:'Folder setup',type:'select',options:[{value:'empty',label:'Empty project'},{value:'asset_shots',label:'Assets / Shots / Outputs'},{value:'product_stills',label:'Models / Lighting / Cameras / Outputs'}]}],v=>run('create',v));
const activity=button('Queue',()=>{selected=null;selectedConnection=null;selectedDataConnection=null;selection.clear();inspect();},'Project render queue');activity.id='queueActivity';toolbar.insertBefore(activity,inspectorToggle);
function queueEntry(q){const entry=el('div',undefined,'renderRun');entry.append(actions(el('strong',q.name),badge(q.status,q.status==='Failed'?'danger':q.status==='Complete'?'good':'')));if(['Queued','Preparing','Rendering'].includes(q.status))entry.append(button('Cancel',()=>run('cancel_queue',{queue_id:q.id})));if(q.error)entry.append(el('p',q.error,'warning'));return entry;}
function updateQueueCount(){const count=(state.project?.render_queue||[]).filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length;activity.textContent='Queue'+(count?' · '+count:'');}
PipelineUI.use('inspect','workflow-details',400,function(next){next();updateQueueCount();const n=state.project?.nodes.find(n=>n.id===selected),pane=$('inspector');if(selectedConnection||selectedDataConnection)return;
  if(!n){if(state.project){const queue=state.project.render_queue||[];pane.prepend(section('Render queue',actions(button('Queue selected files',queueSelection),button('Check project',()=>showPreflight())),...(queue.length?[...queue].reverse().slice(0,15).map(queueEntry):[muted('Select configured files, then View → Queue selected files. Each run uses its own numbered output folder.')])),section('Blender companion',muted('Create or join projects from Blender, save snapshots, link into your working file and report unsaved state.'),button('Companion setup guide',showCompanionGuide)));}return;}
  if(n.type!=='blend')return;const content=pane.querySelector('.uxTabContent');if(!content)return;
  if(inspectorTab==='overview'){const stages=el('select');stages.setAttribute('aria-label','Workflow stage');for(const key of ['draft','working','review','ready','done','blocked']){const o=el('option',typeLabel(key));o.value=key;stages.append(o);}stages.value=n.stage||'draft';stages.onchange=()=>editGraph(n,{stage:stages.value});const box=section('Workflow stage',stages);content.prepend(box);}
  if(inspectorTab==='render'){content.prepend(section('Run controls',actions(button('Preflight',()=>showPreflight(n.id)),button('Add to render queue',()=>n.render_config?run('queue_render',{node_id:n.id}):configureRender(n))),...state.project.render_queue?.filter(q=>q.node_id===n.id).slice(-3).map(queueEntry)||[]));}
});
PipelineUI.use('render','workflow-labels',401,function(next){next();activity.textContent='Queue'+((state.project?.render_queue||[]).filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length?' · '+state.project.render_queue.filter(q=>['Queued','Preparing','Rendering'].includes(q.status)).length:'');for(const n of visibleNodes().filter(n=>n.type==='blend')){const card=document.querySelector(`[data-id="${n.id}"]`);if(n.stage&&n.stage!=='draft'){const stage=badge(typeLabel(n.stage),n.stage==='blocked'?'danger':n.stage==='ready'||n.stage==='done'?'good':'');stage.classList.add('uxStageBadge');card.querySelector('header').after(stage);}}});
function showCompanionGuide(){modal('Blender companion setup',[],()=>{});$('submit').textContent='Done';$('fields').append(muted('1. Keep this tool running from Launch.cmd.\n2. In Blender Preferences → Add-ons, install Pipeline_Companion.zip from disk and enable Pipeline Companion.\n3. Open the 3D View sidebar (N) → Pipeline.\n4. Choose a project folder, then Save into project.\n\nThe connection file is created beside Launch.cmd while the server runs. If the tool moved, update its path in the add-on preferences.'));const a=el('a','Download companion ZIP');a.href='/Pipeline_Companion.zip';a.download='Pipeline_Companion.zip';$('fields').append(a);}
if(state.project)render();
